#ifndef __SPACE_Y_MATHLIB_SWIZZLING_DECL__
  #define __SPACE_Y_MATHLIB_SWIZZLING_DECL__
  
#define __VEC2_SWIZZLE_DECL( T ) \
    __##T##_tuple_2 __xx(); \
    __##T##_tuple_2 __xy(); \
    __##T##_tuple_2 __xi(); \
    __##T##_tuple_2 __yx(); \
    __##T##_tuple_2 __yy(); \
    __##T##_tuple_2 __yi(); \
    __##T##_tuple_2 __ix(); \
    __##T##_tuple_2 __iy(); \
    __##T##_tuple_2 __ii(); \
    __##T##_tuple_3 __xxx(); \
    __##T##_tuple_3 __xxy(); \
    __##T##_tuple_3 __xxi(); \
    __##T##_tuple_3 __xyx(); \
    __##T##_tuple_3 __xyy(); \
    __##T##_tuple_3 __xyi(); \
    __##T##_tuple_3 __xix(); \
    __##T##_tuple_3 __xiy(); \
    __##T##_tuple_3 __xii(); \
    __##T##_tuple_3 __yxx(); \
    __##T##_tuple_3 __yxy(); \
    __##T##_tuple_3 __yxi(); \
    __##T##_tuple_3 __yyx(); \
    __##T##_tuple_3 __yyy(); \
    __##T##_tuple_3 __yyi(); \
    __##T##_tuple_3 __yix(); \
    __##T##_tuple_3 __yiy(); \
    __##T##_tuple_3 __yii(); \
    __##T##_tuple_3 __ixx(); \
    __##T##_tuple_3 __ixy(); \
    __##T##_tuple_3 __ixi(); \
    __##T##_tuple_3 __iyx(); \
    __##T##_tuple_3 __iyy(); \
    __##T##_tuple_3 __iyi(); \
    __##T##_tuple_3 __iix(); \
    __##T##_tuple_3 __iiy(); \
    __##T##_tuple_3 __iii(); \
    __##T##_tuple_4 __xxxx(); \
    __##T##_tuple_4 __xxxy(); \
    __##T##_tuple_4 __xxxi(); \
    __##T##_tuple_4 __xxyx(); \
    __##T##_tuple_4 __xxyy(); \
    __##T##_tuple_4 __xxyi(); \
    __##T##_tuple_4 __xxix(); \
    __##T##_tuple_4 __xxiy(); \
    __##T##_tuple_4 __xxii(); \
    __##T##_tuple_4 __xyxx(); \
    __##T##_tuple_4 __xyxy(); \
    __##T##_tuple_4 __xyxi(); \
    __##T##_tuple_4 __xyyx(); \
    __##T##_tuple_4 __xyyy(); \
    __##T##_tuple_4 __xyyi(); \
    __##T##_tuple_4 __xyix(); \
    __##T##_tuple_4 __xyiy(); \
    __##T##_tuple_4 __xyii(); \
    __##T##_tuple_4 __xixx(); \
    __##T##_tuple_4 __xixy(); \
    __##T##_tuple_4 __xixi(); \
    __##T##_tuple_4 __xiyx(); \
    __##T##_tuple_4 __xiyy(); \
    __##T##_tuple_4 __xiyi(); \
    __##T##_tuple_4 __xiix(); \
    __##T##_tuple_4 __xiiy(); \
    __##T##_tuple_4 __xiii(); \
    __##T##_tuple_4 __yxxx(); \
    __##T##_tuple_4 __yxxy(); \
    __##T##_tuple_4 __yxxi(); \
    __##T##_tuple_4 __yxyx(); \
    __##T##_tuple_4 __yxyy(); \
    __##T##_tuple_4 __yxyi(); \
    __##T##_tuple_4 __yxix(); \
    __##T##_tuple_4 __yxiy(); \
    __##T##_tuple_4 __yxii(); \
    __##T##_tuple_4 __yyxx(); \
    __##T##_tuple_4 __yyxy(); \
    __##T##_tuple_4 __yyxi(); \
    __##T##_tuple_4 __yyyx(); \
    __##T##_tuple_4 __yyyy(); \
    __##T##_tuple_4 __yyyi(); \
    __##T##_tuple_4 __yyix(); \
    __##T##_tuple_4 __yyiy(); \
    __##T##_tuple_4 __yyii(); \
    __##T##_tuple_4 __yixx(); \
    __##T##_tuple_4 __yixy(); \
    __##T##_tuple_4 __yixi(); \
    __##T##_tuple_4 __yiyx(); \
    __##T##_tuple_4 __yiyy(); \
    __##T##_tuple_4 __yiyi(); \
    __##T##_tuple_4 __yiix(); \
    __##T##_tuple_4 __yiiy(); \
    __##T##_tuple_4 __yiii(); \
    __##T##_tuple_4 __ixxx(); \
    __##T##_tuple_4 __ixxy(); \
    __##T##_tuple_4 __ixxi(); \
    __##T##_tuple_4 __ixyx(); \
    __##T##_tuple_4 __ixyy(); \
    __##T##_tuple_4 __ixyi(); \
    __##T##_tuple_4 __ixix(); \
    __##T##_tuple_4 __ixiy(); \
    __##T##_tuple_4 __ixii(); \
    __##T##_tuple_4 __iyxx(); \
    __##T##_tuple_4 __iyxy(); \
    __##T##_tuple_4 __iyxi(); \
    __##T##_tuple_4 __iyyx(); \
    __##T##_tuple_4 __iyyy(); \
    __##T##_tuple_4 __iyyi(); \
    __##T##_tuple_4 __iyix(); \
    __##T##_tuple_4 __iyiy(); \
    __##T##_tuple_4 __iyii(); \
    __##T##_tuple_4 __iixx(); \
    __##T##_tuple_4 __iixy(); \
    __##T##_tuple_4 __iixi(); \
    __##T##_tuple_4 __iiyx(); \
    __##T##_tuple_4 __iiyy(); \
    __##T##_tuple_4 __iiyi(); \
    __##T##_tuple_4 __iiix(); \
    __##T##_tuple_4 __iiiy(); \
    __##T##_tuple_4 __iiii(); \



#define __VEC3_SWIZZLE_DECL( T ) \
    __##T##_tuple_2 __xx(); \
    __##T##_tuple_2 __xy(); \
    __##T##_tuple_2 __xz(); \
    __##T##_tuple_2 __xi(); \
    __##T##_tuple_2 __yx(); \
    __##T##_tuple_2 __yy(); \
    __##T##_tuple_2 __yz(); \
    __##T##_tuple_2 __yi(); \
    __##T##_tuple_2 __zx(); \
    __##T##_tuple_2 __zy(); \
    __##T##_tuple_2 __zz(); \
    __##T##_tuple_2 __zi(); \
    __##T##_tuple_2 __ix(); \
    __##T##_tuple_2 __iy(); \
    __##T##_tuple_2 __iz(); \
    __##T##_tuple_2 __ii(); \
    __##T##_tuple_3 __xxx(); \
    __##T##_tuple_3 __xxy(); \
    __##T##_tuple_3 __xxz(); \
    __##T##_tuple_3 __xxi(); \
    __##T##_tuple_3 __xyx(); \
    __##T##_tuple_3 __xyy(); \
    __##T##_tuple_3 __xyz(); \
    __##T##_tuple_3 __xyi(); \
    __##T##_tuple_3 __xzx(); \
    __##T##_tuple_3 __xzy(); \
    __##T##_tuple_3 __xzz(); \
    __##T##_tuple_3 __xzi(); \
    __##T##_tuple_3 __xix(); \
    __##T##_tuple_3 __xiy(); \
    __##T##_tuple_3 __xiz(); \
    __##T##_tuple_3 __xii(); \
    __##T##_tuple_3 __yxx(); \
    __##T##_tuple_3 __yxy(); \
    __##T##_tuple_3 __yxz(); \
    __##T##_tuple_3 __yxi(); \
    __##T##_tuple_3 __yyx(); \
    __##T##_tuple_3 __yyy(); \
    __##T##_tuple_3 __yyz(); \
    __##T##_tuple_3 __yyi(); \
    __##T##_tuple_3 __yzx(); \
    __##T##_tuple_3 __yzy(); \
    __##T##_tuple_3 __yzz(); \
    __##T##_tuple_3 __yzi(); \
    __##T##_tuple_3 __yix(); \
    __##T##_tuple_3 __yiy(); \
    __##T##_tuple_3 __yiz(); \
    __##T##_tuple_3 __yii(); \
    __##T##_tuple_3 __zxx(); \
    __##T##_tuple_3 __zxy(); \
    __##T##_tuple_3 __zxz(); \
    __##T##_tuple_3 __zxi(); \
    __##T##_tuple_3 __zyx(); \
    __##T##_tuple_3 __zyy(); \
    __##T##_tuple_3 __zyz(); \
    __##T##_tuple_3 __zyi(); \
    __##T##_tuple_3 __zzx(); \
    __##T##_tuple_3 __zzy(); \
    __##T##_tuple_3 __zzz(); \
    __##T##_tuple_3 __zzi(); \
    __##T##_tuple_3 __zix(); \
    __##T##_tuple_3 __ziy(); \
    __##T##_tuple_3 __ziz(); \
    __##T##_tuple_3 __zii(); \
    __##T##_tuple_3 __ixx(); \
    __##T##_tuple_3 __ixy(); \
    __##T##_tuple_3 __ixz(); \
    __##T##_tuple_3 __ixi(); \
    __##T##_tuple_3 __iyx(); \
    __##T##_tuple_3 __iyy(); \
    __##T##_tuple_3 __iyz(); \
    __##T##_tuple_3 __iyi(); \
    __##T##_tuple_3 __izx(); \
    __##T##_tuple_3 __izy(); \
    __##T##_tuple_3 __izz(); \
    __##T##_tuple_3 __izi(); \
    __##T##_tuple_3 __iix(); \
    __##T##_tuple_3 __iiy(); \
    __##T##_tuple_3 __iiz(); \
    __##T##_tuple_3 __iii(); \
    __##T##_tuple_4 __xxxx(); \
    __##T##_tuple_4 __xxxy(); \
    __##T##_tuple_4 __xxxz(); \
    __##T##_tuple_4 __xxxi(); \
    __##T##_tuple_4 __xxyx(); \
    __##T##_tuple_4 __xxyy(); \
    __##T##_tuple_4 __xxyz(); \
    __##T##_tuple_4 __xxyi(); \
    __##T##_tuple_4 __xxzx(); \
    __##T##_tuple_4 __xxzy(); \
    __##T##_tuple_4 __xxzz(); \
    __##T##_tuple_4 __xxzi(); \
    __##T##_tuple_4 __xxix(); \
    __##T##_tuple_4 __xxiy(); \
    __##T##_tuple_4 __xxiz(); \
    __##T##_tuple_4 __xxii(); \
    __##T##_tuple_4 __xyxx(); \
    __##T##_tuple_4 __xyxy(); \
    __##T##_tuple_4 __xyxz(); \
    __##T##_tuple_4 __xyxi(); \
    __##T##_tuple_4 __xyyx(); \
    __##T##_tuple_4 __xyyy(); \
    __##T##_tuple_4 __xyyz(); \
    __##T##_tuple_4 __xyyi(); \
    __##T##_tuple_4 __xyzx(); \
    __##T##_tuple_4 __xyzy(); \
    __##T##_tuple_4 __xyzz(); \
    __##T##_tuple_4 __xyzi(); \
    __##T##_tuple_4 __xyix(); \
    __##T##_tuple_4 __xyiy(); \
    __##T##_tuple_4 __xyiz(); \
    __##T##_tuple_4 __xyii(); \
    __##T##_tuple_4 __xzxx(); \
    __##T##_tuple_4 __xzxy(); \
    __##T##_tuple_4 __xzxz(); \
    __##T##_tuple_4 __xzxi(); \
    __##T##_tuple_4 __xzyx(); \
    __##T##_tuple_4 __xzyy(); \
    __##T##_tuple_4 __xzyz(); \
    __##T##_tuple_4 __xzyi(); \
    __##T##_tuple_4 __xzzx(); \
    __##T##_tuple_4 __xzzy(); \
    __##T##_tuple_4 __xzzz(); \
    __##T##_tuple_4 __xzzi(); \
    __##T##_tuple_4 __xzix(); \
    __##T##_tuple_4 __xziy(); \
    __##T##_tuple_4 __xziz(); \
    __##T##_tuple_4 __xzii(); \
    __##T##_tuple_4 __xixx(); \
    __##T##_tuple_4 __xixy(); \
    __##T##_tuple_4 __xixz(); \
    __##T##_tuple_4 __xixi(); \
    __##T##_tuple_4 __xiyx(); \
    __##T##_tuple_4 __xiyy(); \
    __##T##_tuple_4 __xiyz(); \
    __##T##_tuple_4 __xiyi(); \
    __##T##_tuple_4 __xizx(); \
    __##T##_tuple_4 __xizy(); \
    __##T##_tuple_4 __xizz(); \
    __##T##_tuple_4 __xizi(); \
    __##T##_tuple_4 __xiix(); \
    __##T##_tuple_4 __xiiy(); \
    __##T##_tuple_4 __xiiz(); \
    __##T##_tuple_4 __xiii(); \
    __##T##_tuple_4 __yxxx(); \
    __##T##_tuple_4 __yxxy(); \
    __##T##_tuple_4 __yxxz(); \
    __##T##_tuple_4 __yxxi(); \
    __##T##_tuple_4 __yxyx(); \
    __##T##_tuple_4 __yxyy(); \
    __##T##_tuple_4 __yxyz(); \
    __##T##_tuple_4 __yxyi(); \
    __##T##_tuple_4 __yxzx(); \
    __##T##_tuple_4 __yxzy(); \
    __##T##_tuple_4 __yxzz(); \
    __##T##_tuple_4 __yxzi(); \
    __##T##_tuple_4 __yxix(); \
    __##T##_tuple_4 __yxiy(); \
    __##T##_tuple_4 __yxiz(); \
    __##T##_tuple_4 __yxii(); \
    __##T##_tuple_4 __yyxx(); \
    __##T##_tuple_4 __yyxy(); \
    __##T##_tuple_4 __yyxz(); \
    __##T##_tuple_4 __yyxi(); \
    __##T##_tuple_4 __yyyx(); \
    __##T##_tuple_4 __yyyy(); \
    __##T##_tuple_4 __yyyz(); \
    __##T##_tuple_4 __yyyi(); \
    __##T##_tuple_4 __yyzx(); \
    __##T##_tuple_4 __yyzy(); \
    __##T##_tuple_4 __yyzz(); \
    __##T##_tuple_4 __yyzi(); \
    __##T##_tuple_4 __yyix(); \
    __##T##_tuple_4 __yyiy(); \
    __##T##_tuple_4 __yyiz(); \
    __##T##_tuple_4 __yyii(); \
    __##T##_tuple_4 __yzxx(); \
    __##T##_tuple_4 __yzxy(); \
    __##T##_tuple_4 __yzxz(); \
    __##T##_tuple_4 __yzxi(); \
    __##T##_tuple_4 __yzyx(); \
    __##T##_tuple_4 __yzyy(); \
    __##T##_tuple_4 __yzyz(); \
    __##T##_tuple_4 __yzyi(); \
    __##T##_tuple_4 __yzzx(); \
    __##T##_tuple_4 __yzzy(); \
    __##T##_tuple_4 __yzzz(); \
    __##T##_tuple_4 __yzzi(); \
    __##T##_tuple_4 __yzix(); \
    __##T##_tuple_4 __yziy(); \
    __##T##_tuple_4 __yziz(); \
    __##T##_tuple_4 __yzii(); \
    __##T##_tuple_4 __yixx(); \
    __##T##_tuple_4 __yixy(); \
    __##T##_tuple_4 __yixz(); \
    __##T##_tuple_4 __yixi(); \
    __##T##_tuple_4 __yiyx(); \
    __##T##_tuple_4 __yiyy(); \
    __##T##_tuple_4 __yiyz(); \
    __##T##_tuple_4 __yiyi(); \
    __##T##_tuple_4 __yizx(); \
    __##T##_tuple_4 __yizy(); \
    __##T##_tuple_4 __yizz(); \
    __##T##_tuple_4 __yizi(); \
    __##T##_tuple_4 __yiix(); \
    __##T##_tuple_4 __yiiy(); \
    __##T##_tuple_4 __yiiz(); \
    __##T##_tuple_4 __yiii(); \
    __##T##_tuple_4 __zxxx(); \
    __##T##_tuple_4 __zxxy(); \
    __##T##_tuple_4 __zxxz(); \
    __##T##_tuple_4 __zxxi(); \
    __##T##_tuple_4 __zxyx(); \
    __##T##_tuple_4 __zxyy(); \
    __##T##_tuple_4 __zxyz(); \
    __##T##_tuple_4 __zxyi(); \
    __##T##_tuple_4 __zxzx(); \
    __##T##_tuple_4 __zxzy(); \
    __##T##_tuple_4 __zxzz(); \
    __##T##_tuple_4 __zxzi(); \
    __##T##_tuple_4 __zxix(); \
    __##T##_tuple_4 __zxiy(); \
    __##T##_tuple_4 __zxiz(); \
    __##T##_tuple_4 __zxii(); \
    __##T##_tuple_4 __zyxx(); \
    __##T##_tuple_4 __zyxy(); \
    __##T##_tuple_4 __zyxz(); \
    __##T##_tuple_4 __zyxi(); \
    __##T##_tuple_4 __zyyx(); \
    __##T##_tuple_4 __zyyy(); \
    __##T##_tuple_4 __zyyz(); \
    __##T##_tuple_4 __zyyi(); \
    __##T##_tuple_4 __zyzx(); \
    __##T##_tuple_4 __zyzy(); \
    __##T##_tuple_4 __zyzz(); \
    __##T##_tuple_4 __zyzi(); \
    __##T##_tuple_4 __zyix(); \
    __##T##_tuple_4 __zyiy(); \
    __##T##_tuple_4 __zyiz(); \
    __##T##_tuple_4 __zyii(); \
    __##T##_tuple_4 __zzxx(); \
    __##T##_tuple_4 __zzxy(); \
    __##T##_tuple_4 __zzxz(); \
    __##T##_tuple_4 __zzxi(); \
    __##T##_tuple_4 __zzyx(); \
    __##T##_tuple_4 __zzyy(); \
    __##T##_tuple_4 __zzyz(); \
    __##T##_tuple_4 __zzyi(); \
    __##T##_tuple_4 __zzzx(); \
    __##T##_tuple_4 __zzzy(); \
    __##T##_tuple_4 __zzzz(); \
    __##T##_tuple_4 __zzzi(); \
    __##T##_tuple_4 __zzix(); \
    __##T##_tuple_4 __zziy(); \
    __##T##_tuple_4 __zziz(); \
    __##T##_tuple_4 __zzii(); \
    __##T##_tuple_4 __zixx(); \
    __##T##_tuple_4 __zixy(); \
    __##T##_tuple_4 __zixz(); \
    __##T##_tuple_4 __zixi(); \
    __##T##_tuple_4 __ziyx(); \
    __##T##_tuple_4 __ziyy(); \
    __##T##_tuple_4 __ziyz(); \
    __##T##_tuple_4 __ziyi(); \
    __##T##_tuple_4 __zizx(); \
    __##T##_tuple_4 __zizy(); \
    __##T##_tuple_4 __zizz(); \
    __##T##_tuple_4 __zizi(); \
    __##T##_tuple_4 __ziix(); \
    __##T##_tuple_4 __ziiy(); \
    __##T##_tuple_4 __ziiz(); \
    __##T##_tuple_4 __ziii(); \
    __##T##_tuple_4 __ixxx(); \
    __##T##_tuple_4 __ixxy(); \
    __##T##_tuple_4 __ixxz(); \
    __##T##_tuple_4 __ixxi(); \
    __##T##_tuple_4 __ixyx(); \
    __##T##_tuple_4 __ixyy(); \
    __##T##_tuple_4 __ixyz(); \
    __##T##_tuple_4 __ixyi(); \
    __##T##_tuple_4 __ixzx(); \
    __##T##_tuple_4 __ixzy(); \
    __##T##_tuple_4 __ixzz(); \
    __##T##_tuple_4 __ixzi(); \
    __##T##_tuple_4 __ixix(); \
    __##T##_tuple_4 __ixiy(); \
    __##T##_tuple_4 __ixiz(); \
    __##T##_tuple_4 __ixii(); \
    __##T##_tuple_4 __iyxx(); \
    __##T##_tuple_4 __iyxy(); \
    __##T##_tuple_4 __iyxz(); \
    __##T##_tuple_4 __iyxi(); \
    __##T##_tuple_4 __iyyx(); \
    __##T##_tuple_4 __iyyy(); \
    __##T##_tuple_4 __iyyz(); \
    __##T##_tuple_4 __iyyi(); \
    __##T##_tuple_4 __iyzx(); \
    __##T##_tuple_4 __iyzy(); \
    __##T##_tuple_4 __iyzz(); \
    __##T##_tuple_4 __iyzi(); \
    __##T##_tuple_4 __iyix(); \
    __##T##_tuple_4 __iyiy(); \
    __##T##_tuple_4 __iyiz(); \
    __##T##_tuple_4 __iyii(); \
    __##T##_tuple_4 __izxx(); \
    __##T##_tuple_4 __izxy(); \
    __##T##_tuple_4 __izxz(); \
    __##T##_tuple_4 __izxi(); \
    __##T##_tuple_4 __izyx(); \
    __##T##_tuple_4 __izyy(); \
    __##T##_tuple_4 __izyz(); \
    __##T##_tuple_4 __izyi(); \
    __##T##_tuple_4 __izzx(); \
    __##T##_tuple_4 __izzy(); \
    __##T##_tuple_4 __izzz(); \
    __##T##_tuple_4 __izzi(); \
    __##T##_tuple_4 __izix(); \
    __##T##_tuple_4 __iziy(); \
    __##T##_tuple_4 __iziz(); \
    __##T##_tuple_4 __izii(); \
    __##T##_tuple_4 __iixx(); \
    __##T##_tuple_4 __iixy(); \
    __##T##_tuple_4 __iixz(); \
    __##T##_tuple_4 __iixi(); \
    __##T##_tuple_4 __iiyx(); \
    __##T##_tuple_4 __iiyy(); \
    __##T##_tuple_4 __iiyz(); \
    __##T##_tuple_4 __iiyi(); \
    __##T##_tuple_4 __iizx(); \
    __##T##_tuple_4 __iizy(); \
    __##T##_tuple_4 __iizz(); \
    __##T##_tuple_4 __iizi(); \
    __##T##_tuple_4 __iiix(); \
    __##T##_tuple_4 __iiiy(); \
    __##T##_tuple_4 __iiiz(); \
    __##T##_tuple_4 __iiii(); \



#define __VEC4_SWIZZLE_DECL( T ) \
    __##T##_tuple_2 __xx(); \
    __##T##_tuple_2 __xy(); \
    __##T##_tuple_2 __xz(); \
    __##T##_tuple_2 __xw(); \
    __##T##_tuple_2 __xi(); \
    __##T##_tuple_2 __yx(); \
    __##T##_tuple_2 __yy(); \
    __##T##_tuple_2 __yz(); \
    __##T##_tuple_2 __yw(); \
    __##T##_tuple_2 __yi(); \
    __##T##_tuple_2 __zx(); \
    __##T##_tuple_2 __zy(); \
    __##T##_tuple_2 __zz(); \
    __##T##_tuple_2 __zw(); \
    __##T##_tuple_2 __zi(); \
    __##T##_tuple_2 __wx(); \
    __##T##_tuple_2 __wy(); \
    __##T##_tuple_2 __wz(); \
    __##T##_tuple_2 __ww(); \
    __##T##_tuple_2 __wi(); \
    __##T##_tuple_2 __ix(); \
    __##T##_tuple_2 __iy(); \
    __##T##_tuple_2 __iz(); \
    __##T##_tuple_2 __iw(); \
    __##T##_tuple_2 __ii(); \
    __##T##_tuple_3 __xxx(); \
    __##T##_tuple_3 __xxy(); \
    __##T##_tuple_3 __xxz(); \
    __##T##_tuple_3 __xxw(); \
    __##T##_tuple_3 __xxi(); \
    __##T##_tuple_3 __xyx(); \
    __##T##_tuple_3 __xyy(); \
    __##T##_tuple_3 __xyz(); \
    __##T##_tuple_3 __xyw(); \
    __##T##_tuple_3 __xyi(); \
    __##T##_tuple_3 __xzx(); \
    __##T##_tuple_3 __xzy(); \
    __##T##_tuple_3 __xzz(); \
    __##T##_tuple_3 __xzw(); \
    __##T##_tuple_3 __xzi(); \
    __##T##_tuple_3 __xwx(); \
    __##T##_tuple_3 __xwy(); \
    __##T##_tuple_3 __xwz(); \
    __##T##_tuple_3 __xww(); \
    __##T##_tuple_3 __xwi(); \
    __##T##_tuple_3 __xix(); \
    __##T##_tuple_3 __xiy(); \
    __##T##_tuple_3 __xiz(); \
    __##T##_tuple_3 __xiw(); \
    __##T##_tuple_3 __xii(); \
    __##T##_tuple_3 __yxx(); \
    __##T##_tuple_3 __yxy(); \
    __##T##_tuple_3 __yxz(); \
    __##T##_tuple_3 __yxw(); \
    __##T##_tuple_3 __yxi(); \
    __##T##_tuple_3 __yyx(); \
    __##T##_tuple_3 __yyy(); \
    __##T##_tuple_3 __yyz(); \
    __##T##_tuple_3 __yyw(); \
    __##T##_tuple_3 __yyi(); \
    __##T##_tuple_3 __yzx(); \
    __##T##_tuple_3 __yzy(); \
    __##T##_tuple_3 __yzz(); \
    __##T##_tuple_3 __yzw(); \
    __##T##_tuple_3 __yzi(); \
    __##T##_tuple_3 __ywx(); \
    __##T##_tuple_3 __ywy(); \
    __##T##_tuple_3 __ywz(); \
    __##T##_tuple_3 __yww(); \
    __##T##_tuple_3 __ywi(); \
    __##T##_tuple_3 __yix(); \
    __##T##_tuple_3 __yiy(); \
    __##T##_tuple_3 __yiz(); \
    __##T##_tuple_3 __yiw(); \
    __##T##_tuple_3 __yii(); \
    __##T##_tuple_3 __zxx(); \
    __##T##_tuple_3 __zxy(); \
    __##T##_tuple_3 __zxz(); \
    __##T##_tuple_3 __zxw(); \
    __##T##_tuple_3 __zxi(); \
    __##T##_tuple_3 __zyx(); \
    __##T##_tuple_3 __zyy(); \
    __##T##_tuple_3 __zyz(); \
    __##T##_tuple_3 __zyw(); \
    __##T##_tuple_3 __zyi(); \
    __##T##_tuple_3 __zzx(); \
    __##T##_tuple_3 __zzy(); \
    __##T##_tuple_3 __zzz(); \
    __##T##_tuple_3 __zzw(); \
    __##T##_tuple_3 __zzi(); \
    __##T##_tuple_3 __zwx(); \
    __##T##_tuple_3 __zwy(); \
    __##T##_tuple_3 __zwz(); \
    __##T##_tuple_3 __zww(); \
    __##T##_tuple_3 __zwi(); \
    __##T##_tuple_3 __zix(); \
    __##T##_tuple_3 __ziy(); \
    __##T##_tuple_3 __ziz(); \
    __##T##_tuple_3 __ziw(); \
    __##T##_tuple_3 __zii(); \
    __##T##_tuple_3 __wxx(); \
    __##T##_tuple_3 __wxy(); \
    __##T##_tuple_3 __wxz(); \
    __##T##_tuple_3 __wxw(); \
    __##T##_tuple_3 __wxi(); \
    __##T##_tuple_3 __wyx(); \
    __##T##_tuple_3 __wyy(); \
    __##T##_tuple_3 __wyz(); \
    __##T##_tuple_3 __wyw(); \
    __##T##_tuple_3 __wyi(); \
    __##T##_tuple_3 __wzx(); \
    __##T##_tuple_3 __wzy(); \
    __##T##_tuple_3 __wzz(); \
    __##T##_tuple_3 __wzw(); \
    __##T##_tuple_3 __wzi(); \
    __##T##_tuple_3 __wwx(); \
    __##T##_tuple_3 __wwy(); \
    __##T##_tuple_3 __wwz(); \
    __##T##_tuple_3 __www(); \
    __##T##_tuple_3 __wwi(); \
    __##T##_tuple_3 __wix(); \
    __##T##_tuple_3 __wiy(); \
    __##T##_tuple_3 __wiz(); \
    __##T##_tuple_3 __wiw(); \
    __##T##_tuple_3 __wii(); \
    __##T##_tuple_3 __ixx(); \
    __##T##_tuple_3 __ixy(); \
    __##T##_tuple_3 __ixz(); \
    __##T##_tuple_3 __ixw(); \
    __##T##_tuple_3 __ixi(); \
    __##T##_tuple_3 __iyx(); \
    __##T##_tuple_3 __iyy(); \
    __##T##_tuple_3 __iyz(); \
    __##T##_tuple_3 __iyw(); \
    __##T##_tuple_3 __iyi(); \
    __##T##_tuple_3 __izx(); \
    __##T##_tuple_3 __izy(); \
    __##T##_tuple_3 __izz(); \
    __##T##_tuple_3 __izw(); \
    __##T##_tuple_3 __izi(); \
    __##T##_tuple_3 __iwx(); \
    __##T##_tuple_3 __iwy(); \
    __##T##_tuple_3 __iwz(); \
    __##T##_tuple_3 __iww(); \
    __##T##_tuple_3 __iwi(); \
    __##T##_tuple_3 __iix(); \
    __##T##_tuple_3 __iiy(); \
    __##T##_tuple_3 __iiz(); \
    __##T##_tuple_3 __iiw(); \
    __##T##_tuple_3 __iii(); \
    __##T##_tuple_4 __xxxx(); \
    __##T##_tuple_4 __xxxy(); \
    __##T##_tuple_4 __xxxz(); \
    __##T##_tuple_4 __xxxw(); \
    __##T##_tuple_4 __xxxi(); \
    __##T##_tuple_4 __xxyx(); \
    __##T##_tuple_4 __xxyy(); \
    __##T##_tuple_4 __xxyz(); \
    __##T##_tuple_4 __xxyw(); \
    __##T##_tuple_4 __xxyi(); \
    __##T##_tuple_4 __xxzx(); \
    __##T##_tuple_4 __xxzy(); \
    __##T##_tuple_4 __xxzz(); \
    __##T##_tuple_4 __xxzw(); \
    __##T##_tuple_4 __xxzi(); \
    __##T##_tuple_4 __xxwx(); \
    __##T##_tuple_4 __xxwy(); \
    __##T##_tuple_4 __xxwz(); \
    __##T##_tuple_4 __xxww(); \
    __##T##_tuple_4 __xxwi(); \
    __##T##_tuple_4 __xxix(); \
    __##T##_tuple_4 __xxiy(); \
    __##T##_tuple_4 __xxiz(); \
    __##T##_tuple_4 __xxiw(); \
    __##T##_tuple_4 __xxii(); \
    __##T##_tuple_4 __xyxx(); \
    __##T##_tuple_4 __xyxy(); \
    __##T##_tuple_4 __xyxz(); \
    __##T##_tuple_4 __xyxw(); \
    __##T##_tuple_4 __xyxi(); \
    __##T##_tuple_4 __xyyx(); \
    __##T##_tuple_4 __xyyy(); \
    __##T##_tuple_4 __xyyz(); \
    __##T##_tuple_4 __xyyw(); \
    __##T##_tuple_4 __xyyi(); \
    __##T##_tuple_4 __xyzx(); \
    __##T##_tuple_4 __xyzy(); \
    __##T##_tuple_4 __xyzz(); \
    __##T##_tuple_4 __xyzw(); \
    __##T##_tuple_4 __xyzi(); \
    __##T##_tuple_4 __xywx(); \
    __##T##_tuple_4 __xywy(); \
    __##T##_tuple_4 __xywz(); \
    __##T##_tuple_4 __xyww(); \
    __##T##_tuple_4 __xywi(); \
    __##T##_tuple_4 __xyix(); \
    __##T##_tuple_4 __xyiy(); \
    __##T##_tuple_4 __xyiz(); \
    __##T##_tuple_4 __xyiw(); \
    __##T##_tuple_4 __xyii(); \
    __##T##_tuple_4 __xzxx(); \
    __##T##_tuple_4 __xzxy(); \
    __##T##_tuple_4 __xzxz(); \
    __##T##_tuple_4 __xzxw(); \
    __##T##_tuple_4 __xzxi(); \
    __##T##_tuple_4 __xzyx(); \
    __##T##_tuple_4 __xzyy(); \
    __##T##_tuple_4 __xzyz(); \
    __##T##_tuple_4 __xzyw(); \
    __##T##_tuple_4 __xzyi(); \
    __##T##_tuple_4 __xzzx(); \
    __##T##_tuple_4 __xzzy(); \
    __##T##_tuple_4 __xzzz(); \
    __##T##_tuple_4 __xzzw(); \
    __##T##_tuple_4 __xzzi(); \
    __##T##_tuple_4 __xzwx(); \
    __##T##_tuple_4 __xzwy(); \
    __##T##_tuple_4 __xzwz(); \
    __##T##_tuple_4 __xzww(); \
    __##T##_tuple_4 __xzwi(); \
    __##T##_tuple_4 __xzix(); \
    __##T##_tuple_4 __xziy(); \
    __##T##_tuple_4 __xziz(); \
    __##T##_tuple_4 __xziw(); \
    __##T##_tuple_4 __xzii(); \
    __##T##_tuple_4 __xwxx(); \
    __##T##_tuple_4 __xwxy(); \
    __##T##_tuple_4 __xwxz(); \
    __##T##_tuple_4 __xwxw(); \
    __##T##_tuple_4 __xwxi(); \
    __##T##_tuple_4 __xwyx(); \
    __##T##_tuple_4 __xwyy(); \
    __##T##_tuple_4 __xwyz(); \
    __##T##_tuple_4 __xwyw(); \
    __##T##_tuple_4 __xwyi(); \
    __##T##_tuple_4 __xwzx(); \
    __##T##_tuple_4 __xwzy(); \
    __##T##_tuple_4 __xwzz(); \
    __##T##_tuple_4 __xwzw(); \
    __##T##_tuple_4 __xwzi(); \
    __##T##_tuple_4 __xwwx(); \
    __##T##_tuple_4 __xwwy(); \
    __##T##_tuple_4 __xwwz(); \
    __##T##_tuple_4 __xwww(); \
    __##T##_tuple_4 __xwwi(); \
    __##T##_tuple_4 __xwix(); \
    __##T##_tuple_4 __xwiy(); \
    __##T##_tuple_4 __xwiz(); \
    __##T##_tuple_4 __xwiw(); \
    __##T##_tuple_4 __xwii(); \
    __##T##_tuple_4 __xixx(); \
    __##T##_tuple_4 __xixy(); \
    __##T##_tuple_4 __xixz(); \
    __##T##_tuple_4 __xixw(); \
    __##T##_tuple_4 __xixi(); \
    __##T##_tuple_4 __xiyx(); \
    __##T##_tuple_4 __xiyy(); \
    __##T##_tuple_4 __xiyz(); \
    __##T##_tuple_4 __xiyw(); \
    __##T##_tuple_4 __xiyi(); \
    __##T##_tuple_4 __xizx(); \
    __##T##_tuple_4 __xizy(); \
    __##T##_tuple_4 __xizz(); \
    __##T##_tuple_4 __xizw(); \
    __##T##_tuple_4 __xizi(); \
    __##T##_tuple_4 __xiwx(); \
    __##T##_tuple_4 __xiwy(); \
    __##T##_tuple_4 __xiwz(); \
    __##T##_tuple_4 __xiww(); \
    __##T##_tuple_4 __xiwi(); \
    __##T##_tuple_4 __xiix(); \
    __##T##_tuple_4 __xiiy(); \
    __##T##_tuple_4 __xiiz(); \
    __##T##_tuple_4 __xiiw(); \
    __##T##_tuple_4 __xiii(); \
    __##T##_tuple_4 __yxxx(); \
    __##T##_tuple_4 __yxxy(); \
    __##T##_tuple_4 __yxxz(); \
    __##T##_tuple_4 __yxxw(); \
    __##T##_tuple_4 __yxxi(); \
    __##T##_tuple_4 __yxyx(); \
    __##T##_tuple_4 __yxyy(); \
    __##T##_tuple_4 __yxyz(); \
    __##T##_tuple_4 __yxyw(); \
    __##T##_tuple_4 __yxyi(); \
    __##T##_tuple_4 __yxzx(); \
    __##T##_tuple_4 __yxzy(); \
    __##T##_tuple_4 __yxzz(); \
    __##T##_tuple_4 __yxzw(); \
    __##T##_tuple_4 __yxzi(); \
    __##T##_tuple_4 __yxwx(); \
    __##T##_tuple_4 __yxwy(); \
    __##T##_tuple_4 __yxwz(); \
    __##T##_tuple_4 __yxww(); \
    __##T##_tuple_4 __yxwi(); \
    __##T##_tuple_4 __yxix(); \
    __##T##_tuple_4 __yxiy(); \
    __##T##_tuple_4 __yxiz(); \
    __##T##_tuple_4 __yxiw(); \
    __##T##_tuple_4 __yxii(); \
    __##T##_tuple_4 __yyxx(); \
    __##T##_tuple_4 __yyxy(); \
    __##T##_tuple_4 __yyxz(); \
    __##T##_tuple_4 __yyxw(); \
    __##T##_tuple_4 __yyxi(); \
    __##T##_tuple_4 __yyyx(); \
    __##T##_tuple_4 __yyyy(); \
    __##T##_tuple_4 __yyyz(); \
    __##T##_tuple_4 __yyyw(); \
    __##T##_tuple_4 __yyyi(); \
    __##T##_tuple_4 __yyzx(); \
    __##T##_tuple_4 __yyzy(); \
    __##T##_tuple_4 __yyzz(); \
    __##T##_tuple_4 __yyzw(); \
    __##T##_tuple_4 __yyzi(); \
    __##T##_tuple_4 __yywx(); \
    __##T##_tuple_4 __yywy(); \
    __##T##_tuple_4 __yywz(); \
    __##T##_tuple_4 __yyww(); \
    __##T##_tuple_4 __yywi(); \
    __##T##_tuple_4 __yyix(); \
    __##T##_tuple_4 __yyiy(); \
    __##T##_tuple_4 __yyiz(); \
    __##T##_tuple_4 __yyiw(); \
    __##T##_tuple_4 __yyii(); \
    __##T##_tuple_4 __yzxx(); \
    __##T##_tuple_4 __yzxy(); \
    __##T##_tuple_4 __yzxz(); \
    __##T##_tuple_4 __yzxw(); \
    __##T##_tuple_4 __yzxi(); \
    __##T##_tuple_4 __yzyx(); \
    __##T##_tuple_4 __yzyy(); \
    __##T##_tuple_4 __yzyz(); \
    __##T##_tuple_4 __yzyw(); \
    __##T##_tuple_4 __yzyi(); \
    __##T##_tuple_4 __yzzx(); \
    __##T##_tuple_4 __yzzy(); \
    __##T##_tuple_4 __yzzz(); \
    __##T##_tuple_4 __yzzw(); \
    __##T##_tuple_4 __yzzi(); \
    __##T##_tuple_4 __yzwx(); \
    __##T##_tuple_4 __yzwy(); \
    __##T##_tuple_4 __yzwz(); \
    __##T##_tuple_4 __yzww(); \
    __##T##_tuple_4 __yzwi(); \
    __##T##_tuple_4 __yzix(); \
    __##T##_tuple_4 __yziy(); \
    __##T##_tuple_4 __yziz(); \
    __##T##_tuple_4 __yziw(); \
    __##T##_tuple_4 __yzii(); \
    __##T##_tuple_4 __ywxx(); \
    __##T##_tuple_4 __ywxy(); \
    __##T##_tuple_4 __ywxz(); \
    __##T##_tuple_4 __ywxw(); \
    __##T##_tuple_4 __ywxi(); \
    __##T##_tuple_4 __ywyx(); \
    __##T##_tuple_4 __ywyy(); \
    __##T##_tuple_4 __ywyz(); \
    __##T##_tuple_4 __ywyw(); \
    __##T##_tuple_4 __ywyi(); \
    __##T##_tuple_4 __ywzx(); \
    __##T##_tuple_4 __ywzy(); \
    __##T##_tuple_4 __ywzz(); \
    __##T##_tuple_4 __ywzw(); \
    __##T##_tuple_4 __ywzi(); \
    __##T##_tuple_4 __ywwx(); \
    __##T##_tuple_4 __ywwy(); \
    __##T##_tuple_4 __ywwz(); \
    __##T##_tuple_4 __ywww(); \
    __##T##_tuple_4 __ywwi(); \
    __##T##_tuple_4 __ywix(); \
    __##T##_tuple_4 __ywiy(); \
    __##T##_tuple_4 __ywiz(); \
    __##T##_tuple_4 __ywiw(); \
    __##T##_tuple_4 __ywii(); \
    __##T##_tuple_4 __yixx(); \
    __##T##_tuple_4 __yixy(); \
    __##T##_tuple_4 __yixz(); \
    __##T##_tuple_4 __yixw(); \
    __##T##_tuple_4 __yixi(); \
    __##T##_tuple_4 __yiyx(); \
    __##T##_tuple_4 __yiyy(); \
    __##T##_tuple_4 __yiyz(); \
    __##T##_tuple_4 __yiyw(); \
    __##T##_tuple_4 __yiyi(); \
    __##T##_tuple_4 __yizx(); \
    __##T##_tuple_4 __yizy(); \
    __##T##_tuple_4 __yizz(); \
    __##T##_tuple_4 __yizw(); \
    __##T##_tuple_4 __yizi(); \
    __##T##_tuple_4 __yiwx(); \
    __##T##_tuple_4 __yiwy(); \
    __##T##_tuple_4 __yiwz(); \
    __##T##_tuple_4 __yiww(); \
    __##T##_tuple_4 __yiwi(); \
    __##T##_tuple_4 __yiix(); \
    __##T##_tuple_4 __yiiy(); \
    __##T##_tuple_4 __yiiz(); \
    __##T##_tuple_4 __yiiw(); \
    __##T##_tuple_4 __yiii(); \
    __##T##_tuple_4 __zxxx(); \
    __##T##_tuple_4 __zxxy(); \
    __##T##_tuple_4 __zxxz(); \
    __##T##_tuple_4 __zxxw(); \
    __##T##_tuple_4 __zxxi(); \
    __##T##_tuple_4 __zxyx(); \
    __##T##_tuple_4 __zxyy(); \
    __##T##_tuple_4 __zxyz(); \
    __##T##_tuple_4 __zxyw(); \
    __##T##_tuple_4 __zxyi(); \
    __##T##_tuple_4 __zxzx(); \
    __##T##_tuple_4 __zxzy(); \
    __##T##_tuple_4 __zxzz(); \
    __##T##_tuple_4 __zxzw(); \
    __##T##_tuple_4 __zxzi(); \
    __##T##_tuple_4 __zxwx(); \
    __##T##_tuple_4 __zxwy(); \
    __##T##_tuple_4 __zxwz(); \
    __##T##_tuple_4 __zxww(); \
    __##T##_tuple_4 __zxwi(); \
    __##T##_tuple_4 __zxix(); \
    __##T##_tuple_4 __zxiy(); \
    __##T##_tuple_4 __zxiz(); \
    __##T##_tuple_4 __zxiw(); \
    __##T##_tuple_4 __zxii(); \
    __##T##_tuple_4 __zyxx(); \
    __##T##_tuple_4 __zyxy(); \
    __##T##_tuple_4 __zyxz(); \
    __##T##_tuple_4 __zyxw(); \
    __##T##_tuple_4 __zyxi(); \
    __##T##_tuple_4 __zyyx(); \
    __##T##_tuple_4 __zyyy(); \
    __##T##_tuple_4 __zyyz(); \
    __##T##_tuple_4 __zyyw(); \
    __##T##_tuple_4 __zyyi(); \
    __##T##_tuple_4 __zyzx(); \
    __##T##_tuple_4 __zyzy(); \
    __##T##_tuple_4 __zyzz(); \
    __##T##_tuple_4 __zyzw(); \
    __##T##_tuple_4 __zyzi(); \
    __##T##_tuple_4 __zywx(); \
    __##T##_tuple_4 __zywy(); \
    __##T##_tuple_4 __zywz(); \
    __##T##_tuple_4 __zyww(); \
    __##T##_tuple_4 __zywi(); \
    __##T##_tuple_4 __zyix(); \
    __##T##_tuple_4 __zyiy(); \
    __##T##_tuple_4 __zyiz(); \
    __##T##_tuple_4 __zyiw(); \
    __##T##_tuple_4 __zyii(); \
    __##T##_tuple_4 __zzxx(); \
    __##T##_tuple_4 __zzxy(); \
    __##T##_tuple_4 __zzxz(); \
    __##T##_tuple_4 __zzxw(); \
    __##T##_tuple_4 __zzxi(); \
    __##T##_tuple_4 __zzyx(); \
    __##T##_tuple_4 __zzyy(); \
    __##T##_tuple_4 __zzyz(); \
    __##T##_tuple_4 __zzyw(); \
    __##T##_tuple_4 __zzyi(); \
    __##T##_tuple_4 __zzzx(); \
    __##T##_tuple_4 __zzzy(); \
    __##T##_tuple_4 __zzzz(); \
    __##T##_tuple_4 __zzzw(); \
    __##T##_tuple_4 __zzzi(); \
    __##T##_tuple_4 __zzwx(); \
    __##T##_tuple_4 __zzwy(); \
    __##T##_tuple_4 __zzwz(); \
    __##T##_tuple_4 __zzww(); \
    __##T##_tuple_4 __zzwi(); \
    __##T##_tuple_4 __zzix(); \
    __##T##_tuple_4 __zziy(); \
    __##T##_tuple_4 __zziz(); \
    __##T##_tuple_4 __zziw(); \
    __##T##_tuple_4 __zzii(); \
    __##T##_tuple_4 __zwxx(); \
    __##T##_tuple_4 __zwxy(); \
    __##T##_tuple_4 __zwxz(); \
    __##T##_tuple_4 __zwxw(); \
    __##T##_tuple_4 __zwxi(); \
    __##T##_tuple_4 __zwyx(); \
    __##T##_tuple_4 __zwyy(); \
    __##T##_tuple_4 __zwyz(); \
    __##T##_tuple_4 __zwyw(); \
    __##T##_tuple_4 __zwyi(); \
    __##T##_tuple_4 __zwzx(); \
    __##T##_tuple_4 __zwzy(); \
    __##T##_tuple_4 __zwzz(); \
    __##T##_tuple_4 __zwzw(); \
    __##T##_tuple_4 __zwzi(); \
    __##T##_tuple_4 __zwwx(); \
    __##T##_tuple_4 __zwwy(); \
    __##T##_tuple_4 __zwwz(); \
    __##T##_tuple_4 __zwww(); \
    __##T##_tuple_4 __zwwi(); \
    __##T##_tuple_4 __zwix(); \
    __##T##_tuple_4 __zwiy(); \
    __##T##_tuple_4 __zwiz(); \
    __##T##_tuple_4 __zwiw(); \
    __##T##_tuple_4 __zwii(); \
    __##T##_tuple_4 __zixx(); \
    __##T##_tuple_4 __zixy(); \
    __##T##_tuple_4 __zixz(); \
    __##T##_tuple_4 __zixw(); \
    __##T##_tuple_4 __zixi(); \
    __##T##_tuple_4 __ziyx(); \
    __##T##_tuple_4 __ziyy(); \
    __##T##_tuple_4 __ziyz(); \
    __##T##_tuple_4 __ziyw(); \
    __##T##_tuple_4 __ziyi(); \
    __##T##_tuple_4 __zizx(); \
    __##T##_tuple_4 __zizy(); \
    __##T##_tuple_4 __zizz(); \
    __##T##_tuple_4 __zizw(); \
    __##T##_tuple_4 __zizi(); \
    __##T##_tuple_4 __ziwx(); \
    __##T##_tuple_4 __ziwy(); \
    __##T##_tuple_4 __ziwz(); \
    __##T##_tuple_4 __ziww(); \
    __##T##_tuple_4 __ziwi(); \
    __##T##_tuple_4 __ziix(); \
    __##T##_tuple_4 __ziiy(); \
    __##T##_tuple_4 __ziiz(); \
    __##T##_tuple_4 __ziiw(); \
    __##T##_tuple_4 __ziii(); \
    __##T##_tuple_4 __wxxx(); \
    __##T##_tuple_4 __wxxy(); \
    __##T##_tuple_4 __wxxz(); \
    __##T##_tuple_4 __wxxw(); \
    __##T##_tuple_4 __wxxi(); \
    __##T##_tuple_4 __wxyx(); \
    __##T##_tuple_4 __wxyy(); \
    __##T##_tuple_4 __wxyz(); \
    __##T##_tuple_4 __wxyw(); \
    __##T##_tuple_4 __wxyi(); \
    __##T##_tuple_4 __wxzx(); \
    __##T##_tuple_4 __wxzy(); \
    __##T##_tuple_4 __wxzz(); \
    __##T##_tuple_4 __wxzw(); \
    __##T##_tuple_4 __wxzi(); \
    __##T##_tuple_4 __wxwx(); \
    __##T##_tuple_4 __wxwy(); \
    __##T##_tuple_4 __wxwz(); \
    __##T##_tuple_4 __wxww(); \
    __##T##_tuple_4 __wxwi(); \
    __##T##_tuple_4 __wxix(); \
    __##T##_tuple_4 __wxiy(); \
    __##T##_tuple_4 __wxiz(); \
    __##T##_tuple_4 __wxiw(); \
    __##T##_tuple_4 __wxii(); \
    __##T##_tuple_4 __wyxx(); \
    __##T##_tuple_4 __wyxy(); \
    __##T##_tuple_4 __wyxz(); \
    __##T##_tuple_4 __wyxw(); \
    __##T##_tuple_4 __wyxi(); \
    __##T##_tuple_4 __wyyx(); \
    __##T##_tuple_4 __wyyy(); \
    __##T##_tuple_4 __wyyz(); \
    __##T##_tuple_4 __wyyw(); \
    __##T##_tuple_4 __wyyi(); \
    __##T##_tuple_4 __wyzx(); \
    __##T##_tuple_4 __wyzy(); \
    __##T##_tuple_4 __wyzz(); \
    __##T##_tuple_4 __wyzw(); \
    __##T##_tuple_4 __wyzi(); \
    __##T##_tuple_4 __wywx(); \
    __##T##_tuple_4 __wywy(); \
    __##T##_tuple_4 __wywz(); \
    __##T##_tuple_4 __wyww(); \
    __##T##_tuple_4 __wywi(); \
    __##T##_tuple_4 __wyix(); \
    __##T##_tuple_4 __wyiy(); \
    __##T##_tuple_4 __wyiz(); \
    __##T##_tuple_4 __wyiw(); \
    __##T##_tuple_4 __wyii(); \
    __##T##_tuple_4 __wzxx(); \
    __##T##_tuple_4 __wzxy(); \
    __##T##_tuple_4 __wzxz(); \
    __##T##_tuple_4 __wzxw(); \
    __##T##_tuple_4 __wzxi(); \
    __##T##_tuple_4 __wzyx(); \
    __##T##_tuple_4 __wzyy(); \
    __##T##_tuple_4 __wzyz(); \
    __##T##_tuple_4 __wzyw(); \
    __##T##_tuple_4 __wzyi(); \
    __##T##_tuple_4 __wzzx(); \
    __##T##_tuple_4 __wzzy(); \
    __##T##_tuple_4 __wzzz(); \
    __##T##_tuple_4 __wzzw(); \
    __##T##_tuple_4 __wzzi(); \
    __##T##_tuple_4 __wzwx(); \
    __##T##_tuple_4 __wzwy(); \
    __##T##_tuple_4 __wzwz(); \
    __##T##_tuple_4 __wzww(); \
    __##T##_tuple_4 __wzwi(); \
    __##T##_tuple_4 __wzix(); \
    __##T##_tuple_4 __wziy(); \
    __##T##_tuple_4 __wziz(); \
    __##T##_tuple_4 __wziw(); \
    __##T##_tuple_4 __wzii(); \
    __##T##_tuple_4 __wwxx(); \
    __##T##_tuple_4 __wwxy(); \
    __##T##_tuple_4 __wwxz(); \
    __##T##_tuple_4 __wwxw(); \
    __##T##_tuple_4 __wwxi(); \
    __##T##_tuple_4 __wwyx(); \
    __##T##_tuple_4 __wwyy(); \
    __##T##_tuple_4 __wwyz(); \
    __##T##_tuple_4 __wwyw(); \
    __##T##_tuple_4 __wwyi(); \
    __##T##_tuple_4 __wwzx(); \
    __##T##_tuple_4 __wwzy(); \
    __##T##_tuple_4 __wwzz(); \
    __##T##_tuple_4 __wwzw(); \
    __##T##_tuple_4 __wwzi(); \
    __##T##_tuple_4 __wwwx(); \
    __##T##_tuple_4 __wwwy(); \
    __##T##_tuple_4 __wwwz(); \
    __##T##_tuple_4 __wwww(); \
    __##T##_tuple_4 __wwwi(); \
    __##T##_tuple_4 __wwix(); \
    __##T##_tuple_4 __wwiy(); \
    __##T##_tuple_4 __wwiz(); \
    __##T##_tuple_4 __wwiw(); \
    __##T##_tuple_4 __wwii(); \
    __##T##_tuple_4 __wixx(); \
    __##T##_tuple_4 __wixy(); \
    __##T##_tuple_4 __wixz(); \
    __##T##_tuple_4 __wixw(); \
    __##T##_tuple_4 __wixi(); \
    __##T##_tuple_4 __wiyx(); \
    __##T##_tuple_4 __wiyy(); \
    __##T##_tuple_4 __wiyz(); \
    __##T##_tuple_4 __wiyw(); \
    __##T##_tuple_4 __wiyi(); \
    __##T##_tuple_4 __wizx(); \
    __##T##_tuple_4 __wizy(); \
    __##T##_tuple_4 __wizz(); \
    __##T##_tuple_4 __wizw(); \
    __##T##_tuple_4 __wizi(); \
    __##T##_tuple_4 __wiwx(); \
    __##T##_tuple_4 __wiwy(); \
    __##T##_tuple_4 __wiwz(); \
    __##T##_tuple_4 __wiww(); \
    __##T##_tuple_4 __wiwi(); \
    __##T##_tuple_4 __wiix(); \
    __##T##_tuple_4 __wiiy(); \
    __##T##_tuple_4 __wiiz(); \
    __##T##_tuple_4 __wiiw(); \
    __##T##_tuple_4 __wiii(); \
    __##T##_tuple_4 __ixxx(); \
    __##T##_tuple_4 __ixxy(); \
    __##T##_tuple_4 __ixxz(); \
    __##T##_tuple_4 __ixxw(); \
    __##T##_tuple_4 __ixxi(); \
    __##T##_tuple_4 __ixyx(); \
    __##T##_tuple_4 __ixyy(); \
    __##T##_tuple_4 __ixyz(); \
    __##T##_tuple_4 __ixyw(); \
    __##T##_tuple_4 __ixyi(); \
    __##T##_tuple_4 __ixzx(); \
    __##T##_tuple_4 __ixzy(); \
    __##T##_tuple_4 __ixzz(); \
    __##T##_tuple_4 __ixzw(); \
    __##T##_tuple_4 __ixzi(); \
    __##T##_tuple_4 __ixwx(); \
    __##T##_tuple_4 __ixwy(); \
    __##T##_tuple_4 __ixwz(); \
    __##T##_tuple_4 __ixww(); \
    __##T##_tuple_4 __ixwi(); \
    __##T##_tuple_4 __ixix(); \
    __##T##_tuple_4 __ixiy(); \
    __##T##_tuple_4 __ixiz(); \
    __##T##_tuple_4 __ixiw(); \
    __##T##_tuple_4 __ixii(); \
    __##T##_tuple_4 __iyxx(); \
    __##T##_tuple_4 __iyxy(); \
    __##T##_tuple_4 __iyxz(); \
    __##T##_tuple_4 __iyxw(); \
    __##T##_tuple_4 __iyxi(); \
    __##T##_tuple_4 __iyyx(); \
    __##T##_tuple_4 __iyyy(); \
    __##T##_tuple_4 __iyyz(); \
    __##T##_tuple_4 __iyyw(); \
    __##T##_tuple_4 __iyyi(); \
    __##T##_tuple_4 __iyzx(); \
    __##T##_tuple_4 __iyzy(); \
    __##T##_tuple_4 __iyzz(); \
    __##T##_tuple_4 __iyzw(); \
    __##T##_tuple_4 __iyzi(); \
    __##T##_tuple_4 __iywx(); \
    __##T##_tuple_4 __iywy(); \
    __##T##_tuple_4 __iywz(); \
    __##T##_tuple_4 __iyww(); \
    __##T##_tuple_4 __iywi(); \
    __##T##_tuple_4 __iyix(); \
    __##T##_tuple_4 __iyiy(); \
    __##T##_tuple_4 __iyiz(); \
    __##T##_tuple_4 __iyiw(); \
    __##T##_tuple_4 __iyii(); \
    __##T##_tuple_4 __izxx(); \
    __##T##_tuple_4 __izxy(); \
    __##T##_tuple_4 __izxz(); \
    __##T##_tuple_4 __izxw(); \
    __##T##_tuple_4 __izxi(); \
    __##T##_tuple_4 __izyx(); \
    __##T##_tuple_4 __izyy(); \
    __##T##_tuple_4 __izyz(); \
    __##T##_tuple_4 __izyw(); \
    __##T##_tuple_4 __izyi(); \
    __##T##_tuple_4 __izzx(); \
    __##T##_tuple_4 __izzy(); \
    __##T##_tuple_4 __izzz(); \
    __##T##_tuple_4 __izzw(); \
    __##T##_tuple_4 __izzi(); \
    __##T##_tuple_4 __izwx(); \
    __##T##_tuple_4 __izwy(); \
    __##T##_tuple_4 __izwz(); \
    __##T##_tuple_4 __izww(); \
    __##T##_tuple_4 __izwi(); \
    __##T##_tuple_4 __izix(); \
    __##T##_tuple_4 __iziy(); \
    __##T##_tuple_4 __iziz(); \
    __##T##_tuple_4 __iziw(); \
    __##T##_tuple_4 __izii(); \
    __##T##_tuple_4 __iwxx(); \
    __##T##_tuple_4 __iwxy(); \
    __##T##_tuple_4 __iwxz(); \
    __##T##_tuple_4 __iwxw(); \
    __##T##_tuple_4 __iwxi(); \
    __##T##_tuple_4 __iwyx(); \
    __##T##_tuple_4 __iwyy(); \
    __##T##_tuple_4 __iwyz(); \
    __##T##_tuple_4 __iwyw(); \
    __##T##_tuple_4 __iwyi(); \
    __##T##_tuple_4 __iwzx(); \
    __##T##_tuple_4 __iwzy(); \
    __##T##_tuple_4 __iwzz(); \
    __##T##_tuple_4 __iwzw(); \
    __##T##_tuple_4 __iwzi(); \
    __##T##_tuple_4 __iwwx(); \
    __##T##_tuple_4 __iwwy(); \
    __##T##_tuple_4 __iwwz(); \
    __##T##_tuple_4 __iwww(); \
    __##T##_tuple_4 __iwwi(); \
    __##T##_tuple_4 __iwix(); \
    __##T##_tuple_4 __iwiy(); \
    __##T##_tuple_4 __iwiz(); \
    __##T##_tuple_4 __iwiw(); \
    __##T##_tuple_4 __iwii(); \
    __##T##_tuple_4 __iixx(); \
    __##T##_tuple_4 __iixy(); \
    __##T##_tuple_4 __iixz(); \
    __##T##_tuple_4 __iixw(); \
    __##T##_tuple_4 __iixi(); \
    __##T##_tuple_4 __iiyx(); \
    __##T##_tuple_4 __iiyy(); \
    __##T##_tuple_4 __iiyz(); \
    __##T##_tuple_4 __iiyw(); \
    __##T##_tuple_4 __iiyi(); \
    __##T##_tuple_4 __iizx(); \
    __##T##_tuple_4 __iizy(); \
    __##T##_tuple_4 __iizz(); \
    __##T##_tuple_4 __iizw(); \
    __##T##_tuple_4 __iizi(); \
    __##T##_tuple_4 __iiwx(); \
    __##T##_tuple_4 __iiwy(); \
    __##T##_tuple_4 __iiwz(); \
    __##T##_tuple_4 __iiww(); \
    __##T##_tuple_4 __iiwi(); \
    __##T##_tuple_4 __iiix(); \
    __##T##_tuple_4 __iiiy(); \
    __##T##_tuple_4 __iiiz(); \
    __##T##_tuple_4 __iiiw(); \
    __##T##_tuple_4 __iiii(); \

#endif