#ifndef __SPACE_Y_MATHLIB_SWIZZLING_DECL__
#define __SPACE_Y_MATHLIB_SWIZZLING_DECL__

#define __VEC2_SWIZZLE_DECL( T ) \
    T##vec2 __xx(); \
    T##vec2 __xy(); \
    T##vec2 __xi(); \
    T##vec2 __yx(); \
    T##vec2 __yy(); \
    T##vec2 __yi(); \
    T##vec2 __ix(); \
    T##vec2 __iy(); \
    T##vec2 __ii(); \
    T##vec3 __xxx(); \
    T##vec3 __xxy(); \
    T##vec3 __xxi(); \
    T##vec3 __xyx(); \
    T##vec3 __xyy(); \
    T##vec3 __xyi(); \
    T##vec3 __xix(); \
    T##vec3 __xiy(); \
    T##vec3 __xii(); \
    T##vec3 __yxx(); \
    T##vec3 __yxy(); \
    T##vec3 __yxi(); \
    T##vec3 __yyx(); \
    T##vec3 __yyy(); \
    T##vec3 __yyi(); \
    T##vec3 __yix(); \
    T##vec3 __yiy(); \
    T##vec3 __yii(); \
    T##vec3 __ixx(); \
    T##vec3 __ixy(); \
    T##vec3 __ixi(); \
    T##vec3 __iyx(); \
    T##vec3 __iyy(); \
    T##vec3 __iyi(); \
    T##vec3 __iix(); \
    T##vec3 __iiy(); \
    T##vec3 __iii(); \
    T##vec4 __xxxx(); \
    T##vec4 __xxxy(); \
    T##vec4 __xxxi(); \
    T##vec4 __xxyx(); \
    T##vec4 __xxyy(); \
    T##vec4 __xxyi(); \
    T##vec4 __xxix(); \
    T##vec4 __xxiy(); \
    T##vec4 __xxii(); \
    T##vec4 __xyxx(); \
    T##vec4 __xyxy(); \
    T##vec4 __xyxi(); \
    T##vec4 __xyyx(); \
    T##vec4 __xyyy(); \
    T##vec4 __xyyi(); \
    T##vec4 __xyix(); \
    T##vec4 __xyiy(); \
    T##vec4 __xyii(); \
    T##vec4 __xixx(); \
    T##vec4 __xixy(); \
    T##vec4 __xixi(); \
    T##vec4 __xiyx(); \
    T##vec4 __xiyy(); \
    T##vec4 __xiyi(); \
    T##vec4 __xiix(); \
    T##vec4 __xiiy(); \
    T##vec4 __xiii(); \
    T##vec4 __yxxx(); \
    T##vec4 __yxxy(); \
    T##vec4 __yxxi(); \
    T##vec4 __yxyx(); \
    T##vec4 __yxyy(); \
    T##vec4 __yxyi(); \
    T##vec4 __yxix(); \
    T##vec4 __yxiy(); \
    T##vec4 __yxii(); \
    T##vec4 __yyxx(); \
    T##vec4 __yyxy(); \
    T##vec4 __yyxi(); \
    T##vec4 __yyyx(); \
    T##vec4 __yyyy(); \
    T##vec4 __yyyi(); \
    T##vec4 __yyix(); \
    T##vec4 __yyiy(); \
    T##vec4 __yyii(); \
    T##vec4 __yixx(); \
    T##vec4 __yixy(); \
    T##vec4 __yixi(); \
    T##vec4 __yiyx(); \
    T##vec4 __yiyy(); \
    T##vec4 __yiyi(); \
    T##vec4 __yiix(); \
    T##vec4 __yiiy(); \
    T##vec4 __yiii(); \
    T##vec4 __ixxx(); \
    T##vec4 __ixxy(); \
    T##vec4 __ixxi(); \
    T##vec4 __ixyx(); \
    T##vec4 __ixyy(); \
    T##vec4 __ixyi(); \
    T##vec4 __ixix(); \
    T##vec4 __ixiy(); \
    T##vec4 __ixii(); \
    T##vec4 __iyxx(); \
    T##vec4 __iyxy(); \
    T##vec4 __iyxi(); \
    T##vec4 __iyyx(); \
    T##vec4 __iyyy(); \
    T##vec4 __iyyi(); \
    T##vec4 __iyix(); \
    T##vec4 __iyiy(); \
    T##vec4 __iyii(); \
    T##vec4 __iixx(); \
    T##vec4 __iixy(); \
    T##vec4 __iixi(); \
    T##vec4 __iiyx(); \
    T##vec4 __iiyy(); \
    T##vec4 __iiyi(); \
    T##vec4 __iiix(); \
    T##vec4 __iiiy(); \
    T##vec4 __iiii(); \



#define __VEC3_SWIZZLE_DECL( T ) \
    T##vec2 __xx(); \
    T##vec2 __xy(); \
    T##vec2 __xz(); \
    T##vec2 __xi(); \
    T##vec2 __yx(); \
    T##vec2 __yy(); \
    T##vec2 __yz(); \
    T##vec2 __yi(); \
    T##vec2 __zx(); \
    T##vec2 __zy(); \
    T##vec2 __zz(); \
    T##vec2 __zi(); \
    T##vec2 __ix(); \
    T##vec2 __iy(); \
    T##vec2 __iz(); \
    T##vec2 __ii(); \
    T##vec3 __xxx(); \
    T##vec3 __xxy(); \
    T##vec3 __xxz(); \
    T##vec3 __xxi(); \
    T##vec3 __xyx(); \
    T##vec3 __xyy(); \
    T##vec3 __xyz(); \
    T##vec3 __xyi(); \
    T##vec3 __xzx(); \
    T##vec3 __xzy(); \
    T##vec3 __xzz(); \
    T##vec3 __xzi(); \
    T##vec3 __xix(); \
    T##vec3 __xiy(); \
    T##vec3 __xiz(); \
    T##vec3 __xii(); \
    T##vec3 __yxx(); \
    T##vec3 __yxy(); \
    T##vec3 __yxz(); \
    T##vec3 __yxi(); \
    T##vec3 __yyx(); \
    T##vec3 __yyy(); \
    T##vec3 __yyz(); \
    T##vec3 __yyi(); \
    T##vec3 __yzx(); \
    T##vec3 __yzy(); \
    T##vec3 __yzz(); \
    T##vec3 __yzi(); \
    T##vec3 __yix(); \
    T##vec3 __yiy(); \
    T##vec3 __yiz(); \
    T##vec3 __yii(); \
    T##vec3 __zxx(); \
    T##vec3 __zxy(); \
    T##vec3 __zxz(); \
    T##vec3 __zxi(); \
    T##vec3 __zyx(); \
    T##vec3 __zyy(); \
    T##vec3 __zyz(); \
    T##vec3 __zyi(); \
    T##vec3 __zzx(); \
    T##vec3 __zzy(); \
    T##vec3 __zzz(); \
    T##vec3 __zzi(); \
    T##vec3 __zix(); \
    T##vec3 __ziy(); \
    T##vec3 __ziz(); \
    T##vec3 __zii(); \
    T##vec3 __ixx(); \
    T##vec3 __ixy(); \
    T##vec3 __ixz(); \
    T##vec3 __ixi(); \
    T##vec3 __iyx(); \
    T##vec3 __iyy(); \
    T##vec3 __iyz(); \
    T##vec3 __iyi(); \
    T##vec3 __izx(); \
    T##vec3 __izy(); \
    T##vec3 __izz(); \
    T##vec3 __izi(); \
    T##vec3 __iix(); \
    T##vec3 __iiy(); \
    T##vec3 __iiz(); \
    T##vec3 __iii(); \
    T##vec4 __xxxx(); \
    T##vec4 __xxxy(); \
    T##vec4 __xxxz(); \
    T##vec4 __xxxi(); \
    T##vec4 __xxyx(); \
    T##vec4 __xxyy(); \
    T##vec4 __xxyz(); \
    T##vec4 __xxyi(); \
    T##vec4 __xxzx(); \
    T##vec4 __xxzy(); \
    T##vec4 __xxzz(); \
    T##vec4 __xxzi(); \
    T##vec4 __xxix(); \
    T##vec4 __xxiy(); \
    T##vec4 __xxiz(); \
    T##vec4 __xxii(); \
    T##vec4 __xyxx(); \
    T##vec4 __xyxy(); \
    T##vec4 __xyxz(); \
    T##vec4 __xyxi(); \
    T##vec4 __xyyx(); \
    T##vec4 __xyyy(); \
    T##vec4 __xyyz(); \
    T##vec4 __xyyi(); \
    T##vec4 __xyzx(); \
    T##vec4 __xyzy(); \
    T##vec4 __xyzz(); \
    T##vec4 __xyzi(); \
    T##vec4 __xyix(); \
    T##vec4 __xyiy(); \
    T##vec4 __xyiz(); \
    T##vec4 __xyii(); \
    T##vec4 __xzxx(); \
    T##vec4 __xzxy(); \
    T##vec4 __xzxz(); \
    T##vec4 __xzxi(); \
    T##vec4 __xzyx(); \
    T##vec4 __xzyy(); \
    T##vec4 __xzyz(); \
    T##vec4 __xzyi(); \
    T##vec4 __xzzx(); \
    T##vec4 __xzzy(); \
    T##vec4 __xzzz(); \
    T##vec4 __xzzi(); \
    T##vec4 __xzix(); \
    T##vec4 __xziy(); \
    T##vec4 __xziz(); \
    T##vec4 __xzii(); \
    T##vec4 __xixx(); \
    T##vec4 __xixy(); \
    T##vec4 __xixz(); \
    T##vec4 __xixi(); \
    T##vec4 __xiyx(); \
    T##vec4 __xiyy(); \
    T##vec4 __xiyz(); \
    T##vec4 __xiyi(); \
    T##vec4 __xizx(); \
    T##vec4 __xizy(); \
    T##vec4 __xizz(); \
    T##vec4 __xizi(); \
    T##vec4 __xiix(); \
    T##vec4 __xiiy(); \
    T##vec4 __xiiz(); \
    T##vec4 __xiii(); \
    T##vec4 __yxxx(); \
    T##vec4 __yxxy(); \
    T##vec4 __yxxz(); \
    T##vec4 __yxxi(); \
    T##vec4 __yxyx(); \
    T##vec4 __yxyy(); \
    T##vec4 __yxyz(); \
    T##vec4 __yxyi(); \
    T##vec4 __yxzx(); \
    T##vec4 __yxzy(); \
    T##vec4 __yxzz(); \
    T##vec4 __yxzi(); \
    T##vec4 __yxix(); \
    T##vec4 __yxiy(); \
    T##vec4 __yxiz(); \
    T##vec4 __yxii(); \
    T##vec4 __yyxx(); \
    T##vec4 __yyxy(); \
    T##vec4 __yyxz(); \
    T##vec4 __yyxi(); \
    T##vec4 __yyyx(); \
    T##vec4 __yyyy(); \
    T##vec4 __yyyz(); \
    T##vec4 __yyyi(); \
    T##vec4 __yyzx(); \
    T##vec4 __yyzy(); \
    T##vec4 __yyzz(); \
    T##vec4 __yyzi(); \
    T##vec4 __yyix(); \
    T##vec4 __yyiy(); \
    T##vec4 __yyiz(); \
    T##vec4 __yyii(); \
    T##vec4 __yzxx(); \
    T##vec4 __yzxy(); \
    T##vec4 __yzxz(); \
    T##vec4 __yzxi(); \
    T##vec4 __yzyx(); \
    T##vec4 __yzyy(); \
    T##vec4 __yzyz(); \
    T##vec4 __yzyi(); \
    T##vec4 __yzzx(); \
    T##vec4 __yzzy(); \
    T##vec4 __yzzz(); \
    T##vec4 __yzzi(); \
    T##vec4 __yzix(); \
    T##vec4 __yziy(); \
    T##vec4 __yziz(); \
    T##vec4 __yzii(); \
    T##vec4 __yixx(); \
    T##vec4 __yixy(); \
    T##vec4 __yixz(); \
    T##vec4 __yixi(); \
    T##vec4 __yiyx(); \
    T##vec4 __yiyy(); \
    T##vec4 __yiyz(); \
    T##vec4 __yiyi(); \
    T##vec4 __yizx(); \
    T##vec4 __yizy(); \
    T##vec4 __yizz(); \
    T##vec4 __yizi(); \
    T##vec4 __yiix(); \
    T##vec4 __yiiy(); \
    T##vec4 __yiiz(); \
    T##vec4 __yiii(); \
    T##vec4 __zxxx(); \
    T##vec4 __zxxy(); \
    T##vec4 __zxxz(); \
    T##vec4 __zxxi(); \
    T##vec4 __zxyx(); \
    T##vec4 __zxyy(); \
    T##vec4 __zxyz(); \
    T##vec4 __zxyi(); \
    T##vec4 __zxzx(); \
    T##vec4 __zxzy(); \
    T##vec4 __zxzz(); \
    T##vec4 __zxzi(); \
    T##vec4 __zxix(); \
    T##vec4 __zxiy(); \
    T##vec4 __zxiz(); \
    T##vec4 __zxii(); \
    T##vec4 __zyxx(); \
    T##vec4 __zyxy(); \
    T##vec4 __zyxz(); \
    T##vec4 __zyxi(); \
    T##vec4 __zyyx(); \
    T##vec4 __zyyy(); \
    T##vec4 __zyyz(); \
    T##vec4 __zyyi(); \
    T##vec4 __zyzx(); \
    T##vec4 __zyzy(); \
    T##vec4 __zyzz(); \
    T##vec4 __zyzi(); \
    T##vec4 __zyix(); \
    T##vec4 __zyiy(); \
    T##vec4 __zyiz(); \
    T##vec4 __zyii(); \
    T##vec4 __zzxx(); \
    T##vec4 __zzxy(); \
    T##vec4 __zzxz(); \
    T##vec4 __zzxi(); \
    T##vec4 __zzyx(); \
    T##vec4 __zzyy(); \
    T##vec4 __zzyz(); \
    T##vec4 __zzyi(); \
    T##vec4 __zzzx(); \
    T##vec4 __zzzy(); \
    T##vec4 __zzzz(); \
    T##vec4 __zzzi(); \
    T##vec4 __zzix(); \
    T##vec4 __zziy(); \
    T##vec4 __zziz(); \
    T##vec4 __zzii(); \
    T##vec4 __zixx(); \
    T##vec4 __zixy(); \
    T##vec4 __zixz(); \
    T##vec4 __zixi(); \
    T##vec4 __ziyx(); \
    T##vec4 __ziyy(); \
    T##vec4 __ziyz(); \
    T##vec4 __ziyi(); \
    T##vec4 __zizx(); \
    T##vec4 __zizy(); \
    T##vec4 __zizz(); \
    T##vec4 __zizi(); \
    T##vec4 __ziix(); \
    T##vec4 __ziiy(); \
    T##vec4 __ziiz(); \
    T##vec4 __ziii(); \
    T##vec4 __ixxx(); \
    T##vec4 __ixxy(); \
    T##vec4 __ixxz(); \
    T##vec4 __ixxi(); \
    T##vec4 __ixyx(); \
    T##vec4 __ixyy(); \
    T##vec4 __ixyz(); \
    T##vec4 __ixyi(); \
    T##vec4 __ixzx(); \
    T##vec4 __ixzy(); \
    T##vec4 __ixzz(); \
    T##vec4 __ixzi(); \
    T##vec4 __ixix(); \
    T##vec4 __ixiy(); \
    T##vec4 __ixiz(); \
    T##vec4 __ixii(); \
    T##vec4 __iyxx(); \
    T##vec4 __iyxy(); \
    T##vec4 __iyxz(); \
    T##vec4 __iyxi(); \
    T##vec4 __iyyx(); \
    T##vec4 __iyyy(); \
    T##vec4 __iyyz(); \
    T##vec4 __iyyi(); \
    T##vec4 __iyzx(); \
    T##vec4 __iyzy(); \
    T##vec4 __iyzz(); \
    T##vec4 __iyzi(); \
    T##vec4 __iyix(); \
    T##vec4 __iyiy(); \
    T##vec4 __iyiz(); \
    T##vec4 __iyii(); \
    T##vec4 __izxx(); \
    T##vec4 __izxy(); \
    T##vec4 __izxz(); \
    T##vec4 __izxi(); \
    T##vec4 __izyx(); \
    T##vec4 __izyy(); \
    T##vec4 __izyz(); \
    T##vec4 __izyi(); \
    T##vec4 __izzx(); \
    T##vec4 __izzy(); \
    T##vec4 __izzz(); \
    T##vec4 __izzi(); \
    T##vec4 __izix(); \
    T##vec4 __iziy(); \
    T##vec4 __iziz(); \
    T##vec4 __izii(); \
    T##vec4 __iixx(); \
    T##vec4 __iixy(); \
    T##vec4 __iixz(); \
    T##vec4 __iixi(); \
    T##vec4 __iiyx(); \
    T##vec4 __iiyy(); \
    T##vec4 __iiyz(); \
    T##vec4 __iiyi(); \
    T##vec4 __iizx(); \
    T##vec4 __iizy(); \
    T##vec4 __iizz(); \
    T##vec4 __iizi(); \
    T##vec4 __iiix(); \
    T##vec4 __iiiy(); \
    T##vec4 __iiiz(); \
    T##vec4 __iiii(); \



#define __VEC4_SWIZZLE_DECL( T ) \
    T##vec2 __xx(); \
    T##vec2 __xy(); \
    T##vec2 __xz(); \
    T##vec2 __xw(); \
    T##vec2 __xi(); \
    T##vec2 __yx(); \
    T##vec2 __yy(); \
    T##vec2 __yz(); \
    T##vec2 __yw(); \
    T##vec2 __yi(); \
    T##vec2 __zx(); \
    T##vec2 __zy(); \
    T##vec2 __zz(); \
    T##vec2 __zw(); \
    T##vec2 __zi(); \
    T##vec2 __wx(); \
    T##vec2 __wy(); \
    T##vec2 __wz(); \
    T##vec2 __ww(); \
    T##vec2 __wi(); \
    T##vec2 __ix(); \
    T##vec2 __iy(); \
    T##vec2 __iz(); \
    T##vec2 __iw(); \
    T##vec2 __ii(); \
    T##vec3 __xxx(); \
    T##vec3 __xxy(); \
    T##vec3 __xxz(); \
    T##vec3 __xxw(); \
    T##vec3 __xxi(); \
    T##vec3 __xyx(); \
    T##vec3 __xyy(); \
    T##vec3 __xyz(); \
    T##vec3 __xyw(); \
    T##vec3 __xyi(); \
    T##vec3 __xzx(); \
    T##vec3 __xzy(); \
    T##vec3 __xzz(); \
    T##vec3 __xzw(); \
    T##vec3 __xzi(); \
    T##vec3 __xwx(); \
    T##vec3 __xwy(); \
    T##vec3 __xwz(); \
    T##vec3 __xww(); \
    T##vec3 __xwi(); \
    T##vec3 __xix(); \
    T##vec3 __xiy(); \
    T##vec3 __xiz(); \
    T##vec3 __xiw(); \
    T##vec3 __xii(); \
    T##vec3 __yxx(); \
    T##vec3 __yxy(); \
    T##vec3 __yxz(); \
    T##vec3 __yxw(); \
    T##vec3 __yxi(); \
    T##vec3 __yyx(); \
    T##vec3 __yyy(); \
    T##vec3 __yyz(); \
    T##vec3 __yyw(); \
    T##vec3 __yyi(); \
    T##vec3 __yzx(); \
    T##vec3 __yzy(); \
    T##vec3 __yzz(); \
    T##vec3 __yzw(); \
    T##vec3 __yzi(); \
    T##vec3 __ywx(); \
    T##vec3 __ywy(); \
    T##vec3 __ywz(); \
    T##vec3 __yww(); \
    T##vec3 __ywi(); \
    T##vec3 __yix(); \
    T##vec3 __yiy(); \
    T##vec3 __yiz(); \
    T##vec3 __yiw(); \
    T##vec3 __yii(); \
    T##vec3 __zxx(); \
    T##vec3 __zxy(); \
    T##vec3 __zxz(); \
    T##vec3 __zxw(); \
    T##vec3 __zxi(); \
    T##vec3 __zyx(); \
    T##vec3 __zyy(); \
    T##vec3 __zyz(); \
    T##vec3 __zyw(); \
    T##vec3 __zyi(); \
    T##vec3 __zzx(); \
    T##vec3 __zzy(); \
    T##vec3 __zzz(); \
    T##vec3 __zzw(); \
    T##vec3 __zzi(); \
    T##vec3 __zwx(); \
    T##vec3 __zwy(); \
    T##vec3 __zwz(); \
    T##vec3 __zww(); \
    T##vec3 __zwi(); \
    T##vec3 __zix(); \
    T##vec3 __ziy(); \
    T##vec3 __ziz(); \
    T##vec3 __ziw(); \
    T##vec3 __zii(); \
    T##vec3 __wxx(); \
    T##vec3 __wxy(); \
    T##vec3 __wxz(); \
    T##vec3 __wxw(); \
    T##vec3 __wxi(); \
    T##vec3 __wyx(); \
    T##vec3 __wyy(); \
    T##vec3 __wyz(); \
    T##vec3 __wyw(); \
    T##vec3 __wyi(); \
    T##vec3 __wzx(); \
    T##vec3 __wzy(); \
    T##vec3 __wzz(); \
    T##vec3 __wzw(); \
    T##vec3 __wzi(); \
    T##vec3 __wwx(); \
    T##vec3 __wwy(); \
    T##vec3 __wwz(); \
    T##vec3 __www(); \
    T##vec3 __wwi(); \
    T##vec3 __wix(); \
    T##vec3 __wiy(); \
    T##vec3 __wiz(); \
    T##vec3 __wiw(); \
    T##vec3 __wii(); \
    T##vec3 __ixx(); \
    T##vec3 __ixy(); \
    T##vec3 __ixz(); \
    T##vec3 __ixw(); \
    T##vec3 __ixi(); \
    T##vec3 __iyx(); \
    T##vec3 __iyy(); \
    T##vec3 __iyz(); \
    T##vec3 __iyw(); \
    T##vec3 __iyi(); \
    T##vec3 __izx(); \
    T##vec3 __izy(); \
    T##vec3 __izz(); \
    T##vec3 __izw(); \
    T##vec3 __izi(); \
    T##vec3 __iwx(); \
    T##vec3 __iwy(); \
    T##vec3 __iwz(); \
    T##vec3 __iww(); \
    T##vec3 __iwi(); \
    T##vec3 __iix(); \
    T##vec3 __iiy(); \
    T##vec3 __iiz(); \
    T##vec3 __iiw(); \
    T##vec3 __iii(); \
    T##vec4 __xxxx(); \
    T##vec4 __xxxy(); \
    T##vec4 __xxxz(); \
    T##vec4 __xxxw(); \
    T##vec4 __xxxi(); \
    T##vec4 __xxyx(); \
    T##vec4 __xxyy(); \
    T##vec4 __xxyz(); \
    T##vec4 __xxyw(); \
    T##vec4 __xxyi(); \
    T##vec4 __xxzx(); \
    T##vec4 __xxzy(); \
    T##vec4 __xxzz(); \
    T##vec4 __xxzw(); \
    T##vec4 __xxzi(); \
    T##vec4 __xxwx(); \
    T##vec4 __xxwy(); \
    T##vec4 __xxwz(); \
    T##vec4 __xxww(); \
    T##vec4 __xxwi(); \
    T##vec4 __xxix(); \
    T##vec4 __xxiy(); \
    T##vec4 __xxiz(); \
    T##vec4 __xxiw(); \
    T##vec4 __xxii(); \
    T##vec4 __xyxx(); \
    T##vec4 __xyxy(); \
    T##vec4 __xyxz(); \
    T##vec4 __xyxw(); \
    T##vec4 __xyxi(); \
    T##vec4 __xyyx(); \
    T##vec4 __xyyy(); \
    T##vec4 __xyyz(); \
    T##vec4 __xyyw(); \
    T##vec4 __xyyi(); \
    T##vec4 __xyzx(); \
    T##vec4 __xyzy(); \
    T##vec4 __xyzz(); \
    T##vec4 __xyzw(); \
    T##vec4 __xyzi(); \
    T##vec4 __xywx(); \
    T##vec4 __xywy(); \
    T##vec4 __xywz(); \
    T##vec4 __xyww(); \
    T##vec4 __xywi(); \
    T##vec4 __xyix(); \
    T##vec4 __xyiy(); \
    T##vec4 __xyiz(); \
    T##vec4 __xyiw(); \
    T##vec4 __xyii(); \
    T##vec4 __xzxx(); \
    T##vec4 __xzxy(); \
    T##vec4 __xzxz(); \
    T##vec4 __xzxw(); \
    T##vec4 __xzxi(); \
    T##vec4 __xzyx(); \
    T##vec4 __xzyy(); \
    T##vec4 __xzyz(); \
    T##vec4 __xzyw(); \
    T##vec4 __xzyi(); \
    T##vec4 __xzzx(); \
    T##vec4 __xzzy(); \
    T##vec4 __xzzz(); \
    T##vec4 __xzzw(); \
    T##vec4 __xzzi(); \
    T##vec4 __xzwx(); \
    T##vec4 __xzwy(); \
    T##vec4 __xzwz(); \
    T##vec4 __xzww(); \
    T##vec4 __xzwi(); \
    T##vec4 __xzix(); \
    T##vec4 __xziy(); \
    T##vec4 __xziz(); \
    T##vec4 __xziw(); \
    T##vec4 __xzii(); \
    T##vec4 __xwxx(); \
    T##vec4 __xwxy(); \
    T##vec4 __xwxz(); \
    T##vec4 __xwxw(); \
    T##vec4 __xwxi(); \
    T##vec4 __xwyx(); \
    T##vec4 __xwyy(); \
    T##vec4 __xwyz(); \
    T##vec4 __xwyw(); \
    T##vec4 __xwyi(); \
    T##vec4 __xwzx(); \
    T##vec4 __xwzy(); \
    T##vec4 __xwzz(); \
    T##vec4 __xwzw(); \
    T##vec4 __xwzi(); \
    T##vec4 __xwwx(); \
    T##vec4 __xwwy(); \
    T##vec4 __xwwz(); \
    T##vec4 __xwww(); \
    T##vec4 __xwwi(); \
    T##vec4 __xwix(); \
    T##vec4 __xwiy(); \
    T##vec4 __xwiz(); \
    T##vec4 __xwiw(); \
    T##vec4 __xwii(); \
    T##vec4 __xixx(); \
    T##vec4 __xixy(); \
    T##vec4 __xixz(); \
    T##vec4 __xixw(); \
    T##vec4 __xixi(); \
    T##vec4 __xiyx(); \
    T##vec4 __xiyy(); \
    T##vec4 __xiyz(); \
    T##vec4 __xiyw(); \
    T##vec4 __xiyi(); \
    T##vec4 __xizx(); \
    T##vec4 __xizy(); \
    T##vec4 __xizz(); \
    T##vec4 __xizw(); \
    T##vec4 __xizi(); \
    T##vec4 __xiwx(); \
    T##vec4 __xiwy(); \
    T##vec4 __xiwz(); \
    T##vec4 __xiww(); \
    T##vec4 __xiwi(); \
    T##vec4 __xiix(); \
    T##vec4 __xiiy(); \
    T##vec4 __xiiz(); \
    T##vec4 __xiiw(); \
    T##vec4 __xiii(); \
    T##vec4 __yxxx(); \
    T##vec4 __yxxy(); \
    T##vec4 __yxxz(); \
    T##vec4 __yxxw(); \
    T##vec4 __yxxi(); \
    T##vec4 __yxyx(); \
    T##vec4 __yxyy(); \
    T##vec4 __yxyz(); \
    T##vec4 __yxyw(); \
    T##vec4 __yxyi(); \
    T##vec4 __yxzx(); \
    T##vec4 __yxzy(); \
    T##vec4 __yxzz(); \
    T##vec4 __yxzw(); \
    T##vec4 __yxzi(); \
    T##vec4 __yxwx(); \
    T##vec4 __yxwy(); \
    T##vec4 __yxwz(); \
    T##vec4 __yxww(); \
    T##vec4 __yxwi(); \
    T##vec4 __yxix(); \
    T##vec4 __yxiy(); \
    T##vec4 __yxiz(); \
    T##vec4 __yxiw(); \
    T##vec4 __yxii(); \
    T##vec4 __yyxx(); \
    T##vec4 __yyxy(); \
    T##vec4 __yyxz(); \
    T##vec4 __yyxw(); \
    T##vec4 __yyxi(); \
    T##vec4 __yyyx(); \
    T##vec4 __yyyy(); \
    T##vec4 __yyyz(); \
    T##vec4 __yyyw(); \
    T##vec4 __yyyi(); \
    T##vec4 __yyzx(); \
    T##vec4 __yyzy(); \
    T##vec4 __yyzz(); \
    T##vec4 __yyzw(); \
    T##vec4 __yyzi(); \
    T##vec4 __yywx(); \
    T##vec4 __yywy(); \
    T##vec4 __yywz(); \
    T##vec4 __yyww(); \
    T##vec4 __yywi(); \
    T##vec4 __yyix(); \
    T##vec4 __yyiy(); \
    T##vec4 __yyiz(); \
    T##vec4 __yyiw(); \
    T##vec4 __yyii(); \
    T##vec4 __yzxx(); \
    T##vec4 __yzxy(); \
    T##vec4 __yzxz(); \
    T##vec4 __yzxw(); \
    T##vec4 __yzxi(); \
    T##vec4 __yzyx(); \
    T##vec4 __yzyy(); \
    T##vec4 __yzyz(); \
    T##vec4 __yzyw(); \
    T##vec4 __yzyi(); \
    T##vec4 __yzzx(); \
    T##vec4 __yzzy(); \
    T##vec4 __yzzz(); \
    T##vec4 __yzzw(); \
    T##vec4 __yzzi(); \
    T##vec4 __yzwx(); \
    T##vec4 __yzwy(); \
    T##vec4 __yzwz(); \
    T##vec4 __yzww(); \
    T##vec4 __yzwi(); \
    T##vec4 __yzix(); \
    T##vec4 __yziy(); \
    T##vec4 __yziz(); \
    T##vec4 __yziw(); \
    T##vec4 __yzii(); \
    T##vec4 __ywxx(); \
    T##vec4 __ywxy(); \
    T##vec4 __ywxz(); \
    T##vec4 __ywxw(); \
    T##vec4 __ywxi(); \
    T##vec4 __ywyx(); \
    T##vec4 __ywyy(); \
    T##vec4 __ywyz(); \
    T##vec4 __ywyw(); \
    T##vec4 __ywyi(); \
    T##vec4 __ywzx(); \
    T##vec4 __ywzy(); \
    T##vec4 __ywzz(); \
    T##vec4 __ywzw(); \
    T##vec4 __ywzi(); \
    T##vec4 __ywwx(); \
    T##vec4 __ywwy(); \
    T##vec4 __ywwz(); \
    T##vec4 __ywww(); \
    T##vec4 __ywwi(); \
    T##vec4 __ywix(); \
    T##vec4 __ywiy(); \
    T##vec4 __ywiz(); \
    T##vec4 __ywiw(); \
    T##vec4 __ywii(); \
    T##vec4 __yixx(); \
    T##vec4 __yixy(); \
    T##vec4 __yixz(); \
    T##vec4 __yixw(); \
    T##vec4 __yixi(); \
    T##vec4 __yiyx(); \
    T##vec4 __yiyy(); \
    T##vec4 __yiyz(); \
    T##vec4 __yiyw(); \
    T##vec4 __yiyi(); \
    T##vec4 __yizx(); \
    T##vec4 __yizy(); \
    T##vec4 __yizz(); \
    T##vec4 __yizw(); \
    T##vec4 __yizi(); \
    T##vec4 __yiwx(); \
    T##vec4 __yiwy(); \
    T##vec4 __yiwz(); \
    T##vec4 __yiww(); \
    T##vec4 __yiwi(); \
    T##vec4 __yiix(); \
    T##vec4 __yiiy(); \
    T##vec4 __yiiz(); \
    T##vec4 __yiiw(); \
    T##vec4 __yiii(); \
    T##vec4 __zxxx(); \
    T##vec4 __zxxy(); \
    T##vec4 __zxxz(); \
    T##vec4 __zxxw(); \
    T##vec4 __zxxi(); \
    T##vec4 __zxyx(); \
    T##vec4 __zxyy(); \
    T##vec4 __zxyz(); \
    T##vec4 __zxyw(); \
    T##vec4 __zxyi(); \
    T##vec4 __zxzx(); \
    T##vec4 __zxzy(); \
    T##vec4 __zxzz(); \
    T##vec4 __zxzw(); \
    T##vec4 __zxzi(); \
    T##vec4 __zxwx(); \
    T##vec4 __zxwy(); \
    T##vec4 __zxwz(); \
    T##vec4 __zxww(); \
    T##vec4 __zxwi(); \
    T##vec4 __zxix(); \
    T##vec4 __zxiy(); \
    T##vec4 __zxiz(); \
    T##vec4 __zxiw(); \
    T##vec4 __zxii(); \
    T##vec4 __zyxx(); \
    T##vec4 __zyxy(); \
    T##vec4 __zyxz(); \
    T##vec4 __zyxw(); \
    T##vec4 __zyxi(); \
    T##vec4 __zyyx(); \
    T##vec4 __zyyy(); \
    T##vec4 __zyyz(); \
    T##vec4 __zyyw(); \
    T##vec4 __zyyi(); \
    T##vec4 __zyzx(); \
    T##vec4 __zyzy(); \
    T##vec4 __zyzz(); \
    T##vec4 __zyzw(); \
    T##vec4 __zyzi(); \
    T##vec4 __zywx(); \
    T##vec4 __zywy(); \
    T##vec4 __zywz(); \
    T##vec4 __zyww(); \
    T##vec4 __zywi(); \
    T##vec4 __zyix(); \
    T##vec4 __zyiy(); \
    T##vec4 __zyiz(); \
    T##vec4 __zyiw(); \
    T##vec4 __zyii(); \
    T##vec4 __zzxx(); \
    T##vec4 __zzxy(); \
    T##vec4 __zzxz(); \
    T##vec4 __zzxw(); \
    T##vec4 __zzxi(); \
    T##vec4 __zzyx(); \
    T##vec4 __zzyy(); \
    T##vec4 __zzyz(); \
    T##vec4 __zzyw(); \
    T##vec4 __zzyi(); \
    T##vec4 __zzzx(); \
    T##vec4 __zzzy(); \
    T##vec4 __zzzz(); \
    T##vec4 __zzzw(); \
    T##vec4 __zzzi(); \
    T##vec4 __zzwx(); \
    T##vec4 __zzwy(); \
    T##vec4 __zzwz(); \
    T##vec4 __zzww(); \
    T##vec4 __zzwi(); \
    T##vec4 __zzix(); \
    T##vec4 __zziy(); \
    T##vec4 __zziz(); \
    T##vec4 __zziw(); \
    T##vec4 __zzii(); \
    T##vec4 __zwxx(); \
    T##vec4 __zwxy(); \
    T##vec4 __zwxz(); \
    T##vec4 __zwxw(); \
    T##vec4 __zwxi(); \
    T##vec4 __zwyx(); \
    T##vec4 __zwyy(); \
    T##vec4 __zwyz(); \
    T##vec4 __zwyw(); \
    T##vec4 __zwyi(); \
    T##vec4 __zwzx(); \
    T##vec4 __zwzy(); \
    T##vec4 __zwzz(); \
    T##vec4 __zwzw(); \
    T##vec4 __zwzi(); \
    T##vec4 __zwwx(); \
    T##vec4 __zwwy(); \
    T##vec4 __zwwz(); \
    T##vec4 __zwww(); \
    T##vec4 __zwwi(); \
    T##vec4 __zwix(); \
    T##vec4 __zwiy(); \
    T##vec4 __zwiz(); \
    T##vec4 __zwiw(); \
    T##vec4 __zwii(); \
    T##vec4 __zixx(); \
    T##vec4 __zixy(); \
    T##vec4 __zixz(); \
    T##vec4 __zixw(); \
    T##vec4 __zixi(); \
    T##vec4 __ziyx(); \
    T##vec4 __ziyy(); \
    T##vec4 __ziyz(); \
    T##vec4 __ziyw(); \
    T##vec4 __ziyi(); \
    T##vec4 __zizx(); \
    T##vec4 __zizy(); \
    T##vec4 __zizz(); \
    T##vec4 __zizw(); \
    T##vec4 __zizi(); \
    T##vec4 __ziwx(); \
    T##vec4 __ziwy(); \
    T##vec4 __ziwz(); \
    T##vec4 __ziww(); \
    T##vec4 __ziwi(); \
    T##vec4 __ziix(); \
    T##vec4 __ziiy(); \
    T##vec4 __ziiz(); \
    T##vec4 __ziiw(); \
    T##vec4 __ziii(); \
    T##vec4 __wxxx(); \
    T##vec4 __wxxy(); \
    T##vec4 __wxxz(); \
    T##vec4 __wxxw(); \
    T##vec4 __wxxi(); \
    T##vec4 __wxyx(); \
    T##vec4 __wxyy(); \
    T##vec4 __wxyz(); \
    T##vec4 __wxyw(); \
    T##vec4 __wxyi(); \
    T##vec4 __wxzx(); \
    T##vec4 __wxzy(); \
    T##vec4 __wxzz(); \
    T##vec4 __wxzw(); \
    T##vec4 __wxzi(); \
    T##vec4 __wxwx(); \
    T##vec4 __wxwy(); \
    T##vec4 __wxwz(); \
    T##vec4 __wxww(); \
    T##vec4 __wxwi(); \
    T##vec4 __wxix(); \
    T##vec4 __wxiy(); \
    T##vec4 __wxiz(); \
    T##vec4 __wxiw(); \
    T##vec4 __wxii(); \
    T##vec4 __wyxx(); \
    T##vec4 __wyxy(); \
    T##vec4 __wyxz(); \
    T##vec4 __wyxw(); \
    T##vec4 __wyxi(); \
    T##vec4 __wyyx(); \
    T##vec4 __wyyy(); \
    T##vec4 __wyyz(); \
    T##vec4 __wyyw(); \
    T##vec4 __wyyi(); \
    T##vec4 __wyzx(); \
    T##vec4 __wyzy(); \
    T##vec4 __wyzz(); \
    T##vec4 __wyzw(); \
    T##vec4 __wyzi(); \
    T##vec4 __wywx(); \
    T##vec4 __wywy(); \
    T##vec4 __wywz(); \
    T##vec4 __wyww(); \
    T##vec4 __wywi(); \
    T##vec4 __wyix(); \
    T##vec4 __wyiy(); \
    T##vec4 __wyiz(); \
    T##vec4 __wyiw(); \
    T##vec4 __wyii(); \
    T##vec4 __wzxx(); \
    T##vec4 __wzxy(); \
    T##vec4 __wzxz(); \
    T##vec4 __wzxw(); \
    T##vec4 __wzxi(); \
    T##vec4 __wzyx(); \
    T##vec4 __wzyy(); \
    T##vec4 __wzyz(); \
    T##vec4 __wzyw(); \
    T##vec4 __wzyi(); \
    T##vec4 __wzzx(); \
    T##vec4 __wzzy(); \
    T##vec4 __wzzz(); \
    T##vec4 __wzzw(); \
    T##vec4 __wzzi(); \
    T##vec4 __wzwx(); \
    T##vec4 __wzwy(); \
    T##vec4 __wzwz(); \
    T##vec4 __wzww(); \
    T##vec4 __wzwi(); \
    T##vec4 __wzix(); \
    T##vec4 __wziy(); \
    T##vec4 __wziz(); \
    T##vec4 __wziw(); \
    T##vec4 __wzii(); \
    T##vec4 __wwxx(); \
    T##vec4 __wwxy(); \
    T##vec4 __wwxz(); \
    T##vec4 __wwxw(); \
    T##vec4 __wwxi(); \
    T##vec4 __wwyx(); \
    T##vec4 __wwyy(); \
    T##vec4 __wwyz(); \
    T##vec4 __wwyw(); \
    T##vec4 __wwyi(); \
    T##vec4 __wwzx(); \
    T##vec4 __wwzy(); \
    T##vec4 __wwzz(); \
    T##vec4 __wwzw(); \
    T##vec4 __wwzi(); \
    T##vec4 __wwwx(); \
    T##vec4 __wwwy(); \
    T##vec4 __wwwz(); \
    T##vec4 __wwww(); \
    T##vec4 __wwwi(); \
    T##vec4 __wwix(); \
    T##vec4 __wwiy(); \
    T##vec4 __wwiz(); \
    T##vec4 __wwiw(); \
    T##vec4 __wwii(); \
    T##vec4 __wixx(); \
    T##vec4 __wixy(); \
    T##vec4 __wixz(); \
    T##vec4 __wixw(); \
    T##vec4 __wixi(); \
    T##vec4 __wiyx(); \
    T##vec4 __wiyy(); \
    T##vec4 __wiyz(); \
    T##vec4 __wiyw(); \
    T##vec4 __wiyi(); \
    T##vec4 __wizx(); \
    T##vec4 __wizy(); \
    T##vec4 __wizz(); \
    T##vec4 __wizw(); \
    T##vec4 __wizi(); \
    T##vec4 __wiwx(); \
    T##vec4 __wiwy(); \
    T##vec4 __wiwz(); \
    T##vec4 __wiww(); \
    T##vec4 __wiwi(); \
    T##vec4 __wiix(); \
    T##vec4 __wiiy(); \
    T##vec4 __wiiz(); \
    T##vec4 __wiiw(); \
    T##vec4 __wiii(); \
    T##vec4 __ixxx(); \
    T##vec4 __ixxy(); \
    T##vec4 __ixxz(); \
    T##vec4 __ixxw(); \
    T##vec4 __ixxi(); \
    T##vec4 __ixyx(); \
    T##vec4 __ixyy(); \
    T##vec4 __ixyz(); \
    T##vec4 __ixyw(); \
    T##vec4 __ixyi(); \
    T##vec4 __ixzx(); \
    T##vec4 __ixzy(); \
    T##vec4 __ixzz(); \
    T##vec4 __ixzw(); \
    T##vec4 __ixzi(); \
    T##vec4 __ixwx(); \
    T##vec4 __ixwy(); \
    T##vec4 __ixwz(); \
    T##vec4 __ixww(); \
    T##vec4 __ixwi(); \
    T##vec4 __ixix(); \
    T##vec4 __ixiy(); \
    T##vec4 __ixiz(); \
    T##vec4 __ixiw(); \
    T##vec4 __ixii(); \
    T##vec4 __iyxx(); \
    T##vec4 __iyxy(); \
    T##vec4 __iyxz(); \
    T##vec4 __iyxw(); \
    T##vec4 __iyxi(); \
    T##vec4 __iyyx(); \
    T##vec4 __iyyy(); \
    T##vec4 __iyyz(); \
    T##vec4 __iyyw(); \
    T##vec4 __iyyi(); \
    T##vec4 __iyzx(); \
    T##vec4 __iyzy(); \
    T##vec4 __iyzz(); \
    T##vec4 __iyzw(); \
    T##vec4 __iyzi(); \
    T##vec4 __iywx(); \
    T##vec4 __iywy(); \
    T##vec4 __iywz(); \
    T##vec4 __iyww(); \
    T##vec4 __iywi(); \
    T##vec4 __iyix(); \
    T##vec4 __iyiy(); \
    T##vec4 __iyiz(); \
    T##vec4 __iyiw(); \
    T##vec4 __iyii(); \
    T##vec4 __izxx(); \
    T##vec4 __izxy(); \
    T##vec4 __izxz(); \
    T##vec4 __izxw(); \
    T##vec4 __izxi(); \
    T##vec4 __izyx(); \
    T##vec4 __izyy(); \
    T##vec4 __izyz(); \
    T##vec4 __izyw(); \
    T##vec4 __izyi(); \
    T##vec4 __izzx(); \
    T##vec4 __izzy(); \
    T##vec4 __izzz(); \
    T##vec4 __izzw(); \
    T##vec4 __izzi(); \
    T##vec4 __izwx(); \
    T##vec4 __izwy(); \
    T##vec4 __izwz(); \
    T##vec4 __izww(); \
    T##vec4 __izwi(); \
    T##vec4 __izix(); \
    T##vec4 __iziy(); \
    T##vec4 __iziz(); \
    T##vec4 __iziw(); \
    T##vec4 __izii(); \
    T##vec4 __iwxx(); \
    T##vec4 __iwxy(); \
    T##vec4 __iwxz(); \
    T##vec4 __iwxw(); \
    T##vec4 __iwxi(); \
    T##vec4 __iwyx(); \
    T##vec4 __iwyy(); \
    T##vec4 __iwyz(); \
    T##vec4 __iwyw(); \
    T##vec4 __iwyi(); \
    T##vec4 __iwzx(); \
    T##vec4 __iwzy(); \
    T##vec4 __iwzz(); \
    T##vec4 __iwzw(); \
    T##vec4 __iwzi(); \
    T##vec4 __iwwx(); \
    T##vec4 __iwwy(); \
    T##vec4 __iwwz(); \
    T##vec4 __iwww(); \
    T##vec4 __iwwi(); \
    T##vec4 __iwix(); \
    T##vec4 __iwiy(); \
    T##vec4 __iwiz(); \
    T##vec4 __iwiw(); \
    T##vec4 __iwii(); \
    T##vec4 __iixx(); \
    T##vec4 __iixy(); \
    T##vec4 __iixz(); \
    T##vec4 __iixw(); \
    T##vec4 __iixi(); \
    T##vec4 __iiyx(); \
    T##vec4 __iiyy(); \
    T##vec4 __iiyz(); \
    T##vec4 __iiyw(); \
    T##vec4 __iiyi(); \
    T##vec4 __iizx(); \
    T##vec4 __iizy(); \
    T##vec4 __iizz(); \
    T##vec4 __iizw(); \
    T##vec4 __iizi(); \
    T##vec4 __iiwx(); \
    T##vec4 __iiwy(); \
    T##vec4 __iiwz(); \
    T##vec4 __iiww(); \
    T##vec4 __iiwi(); \
    T##vec4 __iiix(); \
    T##vec4 __iiiy(); \
    T##vec4 __iiiz(); \
    T##vec4 __iiiw(); \
    T##vec4 __iiii(); \

#endif